### ISSUE TITLE
Payments

### ISSUE THREAD

**Issue by s1-mikey** [LaravelDaily/laravel-invoices#10]
**Is your feature request related to a problem? Please describe.**
Do you have any plans to implement adding payments to invoices? We have use cases where an invoice would have prepayment made.

**Describe the solution you'd like**
It would be good to have either a method to add total payments e.g paymentsTotalAmount() that would be removed from an invoice amount owed total. A brilliant solution would be to be able to add payment items to the invoice to be displayed in a separate area.

**Comment by PovilasKorop** [comment]
@s1-mikey currently this is not in plans, our team is now focused on other projects and not planning to implement new features in this package (unless it's needed for our own clients), but we accept Pull Requests if you want to contribute and build it.

**Comment by MikeyAlder** [comment]
@PovilasKorop Okay, I will work on implementing payments and then create a pull request to share.
