### ISSUE TITLE
Page Breaks

### ISSUE THREAD

**Issue by MrX123123** [LaravelDaily/laravel-invoices#100]
Hi,

how is it possible to implement page breaks with laravel-invoices?
I have read about using <div style="page-break-after:always;"> but this jeopardized my page layout. Is there an other way to archive this?

BR

**Comment by innobv8** [comment]
I implemented page breaks using a similar style from barryvdh/laravel-dompdf:

<style>
.page-break {
    page-break-after: always;
}
</style>
<h1>Page 1</h1>
<div class="page-break"></div>
<h1>Page 2</h1>
