### ISSUE TITLE
setCustomdata() is not defined.

### ISSUE THREAD

**Issue by faizan-glowlogix** [LaravelDaily/laravel-invoices#103]
When I try to use setCustomData() function it gives me this error. it is defined or not? that's how i am sending custom data to the invoice.

`$invoice->setCustomData(['name'=>'test']);`

```
Error
Call to undefined method LaravelDaily\Invoices\Invoice::setCustomData()
```

**Comment by mc0de** [comment]
make sure you have latest version of package

**Comment by faizan-glowlogix** [comment]
@mc0de I have this version and I am guessing this is the latest?
`
"laraveldaily/laravel-invoices": "2.0",`

**Comment by mc0de** [comment]
latest is 2.0.7

**Comment by faizan-glowlogix** [comment]
@mc0de after updating still the same issue.

**Comment by mc0de** [comment]
@faizan-glowlogix i just checked on new installation, everything works as expected
