### ISSUE TITLE
Class dompdf.wrapper does not exist

### ISSUE THREAD

**Issue by EntroSolutions** [LaravelDaily/laravel-invoices#106]
Just generate new PDF with stream it and after successful install 
I got "Class dompdf.wrapper does not exist" I think this dependency must come from your package
or to be loaded properly

**Comment by mc0de** [comment]
this is actually not the problem with package itself
https://www.google.com/search?q=Class+dompdf.wrapper+does+not+exist
might be some issues with a DomPDF dependency and/or autoloading and namespaces

**Comment by EntroSolutions** [comment]
Nop it was, you can include it in your documentation, for all Laravel versions before auto-discovery 
the developer needs to add the dom PDF class and Facade in his config/app.php
