### ISSUE TITLE
i have used url() method but it did not save the file it is just returning the dummy url

### ISSUE THREAD

**Issue by iampankajprasadgupta** [LaravelDaily/laravel-invoices#107]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mc0de** [comment]
you need to explicitly call ->save() and specify disk where you want to save your invoice because package is not automatically aware of your file structure and where do you want to save it before using url() method
