### ISSUE TITLE
Adding included price tax

### ISSUE THREAD

**Issue by MoAlloh** [LaravelDaily/laravel-invoices#109]
Hi,
I would like to ask if there is any method to make the taxByPercent for Items included in the total unit price.

For example:
Units 10
PricePerUnit 10$
TaxByPercent 20%

Result: 
Tax Amount: 20$
Net Price: 80$
Total Price: 100$

**Comment by mc0de** [comment]
you can already do that with taxByPercent() method on item

**Comment by MoAlloh** [comment]
Am using TaxByPercent() but it added the tax amount extra to the total unit price.

This is what I get
Units: 10 
Unit price: 10 
Tax by percent: 20%
Total: 120 (Unit * Unitprice + Tax)


My question if I can get this:
Units: 10
Unit price: 10
Tax by percent: 20%
Total: 100 (unit * Unit Price)

Thanks alot
