### ISSUE TITLE
Logo image not showing

### ISSUE THREAD

**Issue by mtrnik** [LaravelDaily/laravel-invoices#11]
**Describe the bug**
I don't see any logo when I use sample code from documentation. Instead of logo there is only whitespace. 

**To Reproduce**
1. Use sample code from Advanced Usage part of documentation. There is line `->logo(public_path('vendor/invoices/sample-logo.png'))`
2. Save the document
3. Open saved file.

**Expected behavior**
There should be sample-logo.png in the page header. 

**Screenshots**
![bug-invoice](https://user-images.githubusercontent.com/12171220/73939068-f1872580-48e8-11ea-9333-b4f24a5fab36.png)

**Desktop (please complete the following information):**
 - Laravel 6.x
 - PHP 7.3
 - laravel-invoices 1.3

**Additional context**
When I try other PNG images, they have wrong colors (for example background which should be white is black and text which should be black is white).

**Comment by mc0de** [comment]
@mtrnik hi, im not able reproduce your issue. might your system issue or need additional information, also try to update the package.

Please refer to Dompdf documentation on php module requirements here https://github.com/dompdf/dompdf/wiki/Requirements

**Comment by mtrnik** [comment]
> @mtrnik hi, im not able reproduce your issue. might be your system issue or need additional information, also try to update the package.
> 
> Please refer to Dompdf documentation on php module requirements here https://github.com/dompdf/dompdf/wiki/Requirements

Just FYI, it is still not working on Mac with MAMP running. I really don't know why. When I pushed it to linux server, everything was alright.

**Comment by mc0de** [comment]
@mtrnik then it means it is something wrong with MAMP configuration and redistributed php libraries, it is not package related

in case you find a way to make it work, let us now
