### ISSUE TITLE
Invoice status like "paid", "due" etc.

### ISSUE THREAD

**Issue by itskawsar** [LaravelDaily/laravel-invoices#112]
**Is your feature request related to a problem?**
An invoice should have a status like *Paid*, *Due* etc.

**Describe the solution you'd like**
Invoice status will describe the state of an invoice. Customers can ask for the invoice after making the whole or partial payment. Then the invoice should have a mark that the invoice is paid or partially paid. Or the invoice is not paid yet, it means the invoice is Due.
Developer can add the status on the `Invoice` class like following:
`Invoice::make('receipt')->status('Paid')->....`

Then the template should show the status.

**Describe alternatives you've considered**
Alternatively, the status can be shown as a watermark. 

**Additional context**
![invoice status example](https://thumbs.dreamstime.com/z/invoice-bills-paid-stamp-close-up-red-document-paperwork-36933430.jpg "Invoice paid status")

**Comment by mc0de** [comment]
we currently have no plans by adding this feature, feel free to submit a PR
