### ISSUE TITLE
Overlapping Names - Buyer Seller Names Displaying in one line

### ISSUE THREAD

**Issue by laxit-patel** [LaravelDaily/laravel-invoices#117]
**Describe the bug**
A simple initialization with 
code copy pasted from git repo
and it generated odd result. 
please help

**Screenshots**
![image](https://user-images.githubusercontent.com/24682969/138584671-0b3445ab-0e97-46e5-8e57-d9010e7fd508.png)

**Comment by jumarjuaton** [comment]
Can you post blade code here? I have encountered too, but I forgot how I solved it.

**Comment by mc0de** [comment]
i can only suggest to follow installation instructions, not sufficient information
