### ISSUE TITLE
Conditionally  push options

### ISSUE THREAD

**Issue by salmanpatnee** [LaravelDaily/laravel-invoices#118]
**Is your feature request related to a problem? Please describe.**
When we make an invoice with different available options we can not push options conditionally. 
It would be great if we can push options conditionally like if vat is applicable then add `taxRate` option otherwise not. 
Right now I have to pass 0 if vat is not applicable. Because of 0 in PDFs it is showing taxable amount: XXXX and tax rate: 0, Which is not ideal

**Comment by drbornot** [comment]
In that way, please if is possible consider make optional the paidUntilDay value, once I can have a status 'Paid' invoice and there's no need to print it in the document. Thanks guys

**Comment by jumarjuaton** [comment]
@salmanpatnee @drbornot I guess you can manually make conditions on your blade file for now. You can also add these fields in Buyer object:

Put all your custom fields on an array in Buyer object.

```
$custom = new Buyer([
            'custom' => [
                'key1' => 'field 1',
                'key2' => 'field 2',
                'key3' => 'field 3',,
]);
```

Have invoice options like: `$invoice = Invoice::make()->buyer($custom)`

Then on your blade file call it like this:` {{ $invoice->buyer->custom['field1']) }}`

You can wrap around these with your conditions.

**Comment by mc0de** [comment]
pseudo code:

```php
$invoice = new Invoice();

if (i have vat applicable) {
    $invoice->taxRate();
}
```

or another option to extend invoice class:

```php

use Illuminate\Support\Traits\Macroable;

class MyInvoice extends Invoice {
    use Macroable {
        __call as __macro_call;
    }

    public function __call($name, $arguments)
    {
        if (Str::endsWith($name, $conditions = ['If', 'Unless', 'IfNotNull'])) {
            foreach ($conditions as $condition) {
                if (!method_exists($this, $method = str_replace($condition, '', $name))) {
                    continue;
                }

                return $this->callConditionalMethod($condition, $method, $arguments);
            }
        }

        return $this->__macro_call($name, $arguments);
    }
}
```

then you can append any method with keywords `If`, `Unless`, `IfNotNull`

`$invoice->taxRateIf(1== 1, $value);`

maybe i will add this in the future, or feel free to submit PR
