### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by joelNguyenn1010** [LaravelDaily/laravel-invoices#12]
How can I use laravel-invoices with lumen?
I'm having a problem with register InvoiceServiceProvider in Lumen

$app->register(LaravelDaily\Invoices\InvoiceServiceProvider::class);

and it gave me this error
  Call to undefined function LaravelDaily\Invoices\config_path()

**Comment by PovilasKorop** [comment]
No, this package wasn't built for Lumen.
