### ISSUE TITLE
Call to undefined method LaravelDaily\Invoices\Classes\InvoiceItem::description()

### ISSUE THREAD

**Issue by salmanpatnee** [LaravelDaily/laravel-invoices#120]
**Describe the bug**
Invoice description method is undefined. 

`Call to undefined method LaravelDaily\Invoices\Classes\InvoiceItem::description()`

**To Reproduce**

**Expected behavior**
Show description in invoice.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mc0de** [comment]
@salmanpatnee description is not static method
