### ISSUE TITLE
Download pdf with Livewire doesn't do anything.

### ISSUE THREAD

**Issue by mark1828** [LaravelDaily/laravel-invoices#128]
Hi, I have a simpel button where I want to download my PDF. But when I click, nothing happens. 

![pdf_bug](https://user-images.githubusercontent.com/32937993/145437670-a4df1ffd-28fa-4eca-bffa-eae147c6074a.gif)

So I tried a different download strategy, like so:

```
$path       = public_path('Bla.pdf');
$contents   = base64_decode('filecode');

//store file temporarily
file_put_contents($path, $contents);

//download file and delete it
return response()->download($path)->deleteFileAfterSend(true);

```

![pdf_works](https://user-images.githubusercontent.com/32937993/145437736-c4cf5913-8dea-4b9a-aabf-9f7771068d72.gif)

And this one downloads the file successfully. How is it not possible to download the PDF with `return $invoice->download();` 

Any suggestions on how to accomplish this? Because I want to edit my invoice with livewire and download it, so it's not possible to redirect to an another controller and download it there. I must download it in that method.

**Comment by mc0de** [comment]
it is hard to understand what the actual problem is, please follow issue template and provide more information

**Comment by mark1828** [comment]
> it is hard to understand what the actual problem is, please follow issue template and provide more information
> 
> this was released before livewire and intended to use with controllers, probably response is not what livewire expects

Well my question is at the last sentence. Do you know a way to download the pdf file with Livewire? The actuall pdf

**Comment by smartified** [comment]
If you want livewire to work

return response()->streamDownload(
            fn() => print($invoice->render()->output),
            "invoice.pdf"
        );
