### ISSUE TITLE
Could not generate invoice

### ISSUE THREAD

**Issue by butrintmetaj** [LaravelDaily/laravel-invoices#129]
When I try to generate an invoice with the package version 2.2 this error is generated.
------------------------------------
#message: """
    Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
    error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed (View: /Users/user1/Sites/site-api/resources/views/vendor/invoices/templates/default.blade.php)
    """
  #code: 0
  #file: "/Users/user1/Sites/site-api/vendor/laraveldaily/laravel-invoices/src/Invoice.php"
  #line: 258
-----------------------------------

**Comment by mc0de** [comment]
@butrintmetaj could you please provide a snippet?

**Comment by mc0de** [comment]
no reply, closing.
