### ISSUE TITLE
Target class [] does not exist.

### ISSUE THREAD

**Issue by HerrTxbias** [LaravelDaily/laravel-invoices#13]
When I'm trying to implement, one of your samples, I'm getting the following Error:
`Target class [] does not exist.`

**Screenshots**
![image](https://user-images.githubusercontent.com/16502676/75253894-b4bf9780-57df-11ea-9567-daf67fb811d1.png)
![image](https://user-images.githubusercontent.com/16502676/75254080-16800180-57e0-11ea-8371-5bef23ee8ad4.png)

**Comment by PovilasKorop** [comment]
@HerrTxbias why do you implement that inside of `routes/web.php` file, and not in a Controller? Probably some class isn't found because of namespaces. Routes file isn't a class, so it's not the best place to write any such code.

**Comment by HerrTxbias** [comment]
I've putted it now in a Controller, but there i got the same problem.

**Comment by PovilasKorop** [comment]
@HerrTxbias please post full code of the controller, and I will try to reproduce

**Comment by HerrTxbias** [comment]
`<?php

namespace App\Http\Controllers;

use App\Blocking;
use App\Booking;
use App\Customer;
use App\Price;
use App\Room;
use DateTime;
use Illuminate\Http\Request;
use LaravelDaily\Invoices\Classes\InvoiceItem;
use LaravelDaily\Invoices\Classes\Party;
use LaravelDaily\Invoices\Invoice;

class InvoiceController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     * @throws \Exception
     */
    public function index($id)
    {
        $booking = Booking::find($id);
        $customer = Customer::find($booking->customer);
        $diff = date_diff(new DateTime(date('d.m.Y', strtotime($booking->end))), new DateTime(date('d.m.Y', strtotime($booking->start))))->format('%a');
        $price = Price::find(Room::find($booking->room)->price);
        $room = Room::find($booking->room);

        $rabatt_ab = 0;
        $rabatt_wert = 0;
        $rabatte = explode(";", setting('preise.discounts'));

        $added = false;
        foreach ($rabatte as $r){
            $rab = explode(":", $r);
            if(!$added && $diff >= intval($rab[0])){
                $rabatt_ab = intval($rab[0]);
                $rabatt_wert = intval($rab[1]);
                $added = true;
            }
        }

        $client = new Party([
            'name'          => $customer->name,
            //'phone'         => '(520) 318-9486',
            //'custom_fields' => [
            //    'note'        => 'IDDQD',
            //    'business id' => '365#GG',
            //],
        ]);

        $customer = new Party([
            'name'          => setting('site.title'),
            //'address'       => 'The Green Street 12',
            //'code'          => '#22663214',
            //'custom_fields' => [
            //    'order number' => '> 654321 <',
            //],
        ]);

        $item = (new InvoiceItem())->title('Raumbuchung: '.$room->descr)->pricePerUnit($price->per_night)->quantity($diff);

        if($added){
            $item->discount($diff * $price->per_night * ($rabatt_wert/100));
        }

        $items = [
            $item,
            (new InvoiceItem())->title('ab '.$rabatt_ab.' Nächte Rabatt ('.$rabatt_wert.'%)'),
        ];

        $notes = [
            'your multiline',
            'additional notes',
            'in regards of delivery or something else',
        ];
        $notes = implode("<br>", $notes);

        $invoice = Invoice::make('receipt')
            ->series('BIG')
            ->sequence($booking->id)
            ->serialNumberFormat('{SEQUENCE}/{SERIES}')
            ->seller($client)
            ->buyer($customer)
            ->date(now()->subWeeks(3))
            ->dateFormat('d.m.Y')
            ->payUntilDays(14)
            ->currencySymbol('€')
            ->currencyCode('EUR')
            ->currencyFormat('{SYMBOL}{VALUE}')
            ->currencyThousandsSeparator('.')
            ->currencyDecimalPoint(',')
            ->filename($client->name . ' ' . $customer->name)
            ->addItems($items)
            //->notes($notes)
            ->logo(public_path('vendor/invoices/sample-logo.png'))
            // You can additionally save generated invoice to configured disk
            ->save('public');

        $link = $invoice->url();
        // Then send email to party with link

        // And return invoice itself to browser or have a different view
        return $invoice->stream();
    }
}
`

**Comment by PovilasKorop** [comment]
@HerrTxbias unfortunately can't reproduce it in full because I don't have any other of your classes and models, but tried to play around hardcoding some values instead of your variables, and it works well for me. 
<img width="780" alt="Screen Shot 2020-02-25 at 9 40 30 PM" src="https://user-images.githubusercontent.com/1510147/75281238-92497080-5817-11ea-9fd1-31c180a93c41.png">

So maybe you can create Github project separately in full and assign me as a collaborator, then I could fully debug if I install full project locally. Otherwise I can't reproduce, sorry.

**Comment by marayshi** [comment]
Hi

For any one face this issue
You just need to clear caches, view etc

```
php artisan config:clear
php artisan cache:clear
php artisan view:clear
php artisan clear-compiled
php artisan config:cache
```

**Comment by ivofrancisco** [comment]
Thank you very much Marayshi.
It worked for me.

**Comment by matthaselip** [comment]
this is because the config file is not loaded as soon as you install the package.  so soon as you have installed it, run php artisan config:cache so that the system can see the config/invoice.php file.  

would help if the instructions were updated to accommodate this.

**Comment by ivofrancisco** [comment]
Thank you very much.

matthaselip <notifications@github.com> escreveu no dia quarta, 9/12/2020
à(s) 14:22:

**Comment by MedAmineBenaicha** [comment]
Thank you very much Marayshi.
