### ISSUE TITLE
call to undefined method status & description

### ISSUE THREAD

**Issue by zidnim5** [LaravelDaily/laravel-invoices#130]
```
$items = [
            (new InvoiceItem())
                ->title('Service 1')
                ->description('Your product or service description') // here is the problem
                ->pricePerUnit(47.79)
                ->quantity(2)
                ->discount(10),
        ];
```
```
  $invoice = Invoice::make('receipt')
            ->series('BIG')
            ->status(__('invoices::invoice.paid')) // here is the problem
            ->sequence(667)
```
1.  Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method LaravelDaily\Invoices\Classes\InvoiceItem::description()
2. Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method LaravelDaily\Invoices\Invoice::status()

package version : 1.3 
laravel version : 5.8

**Comment by PovilasKorop** [comment]
@zidnim5 invoice status was introduced in v2.2 of the package.
Description was also added pretty recently.

So please update the package.
