### ISSUE TITLE
toHtml() is not supported anymore?

### ISSUE THREAD

**Issue by safarovitch** [LaravelDaily/laravel-invoices#133]
**Is your feature request related to a problem? Please describe.**
I see this package does not provide html instead of pdf anymore.
I tried to make html generator myself but its pretty complicated for me.

**Describe the solution you'd like**
I would love to see toHtml() function working again. Is there any chance to use this future or are you planning to add it back sometimes soon.

**Comment by mc0de** [comment]
@safarovitch fixed, please update to v2.2.2
