### ISSUE TITLE
Extend customData() method to accept array

### ISSUE THREAD

**Issue by denvit** [LaravelDaily/laravel-invoices#134]
**Is your feature request related to a problem? Please describe.**
I've recently started using this module on one project and need a way to attach an array of custom data to the invoice.  

**Describe the solution you'd like**
Need a way to be able to use more data on the invoice template. 

**Describe alternatives you've considered**
Extend a customData() method to accept an array as an argument so that this will be possible.

**Additional context**

**Comment by mc0de** [comment]
@denvit 
does `->setCustomData(['data' => 'my data'])` and `->getCustomData()['data']` doesn't work?
