### ISSUE TITLE
Class 'NumberFormatter' not found

### ISSUE THREAD

**Issue by mar846** [LaravelDaily/laravel-invoices#138]
Hi, so i installed laravel-invoices v2.2
and i tested it like this

```
$customer = new Buyer([
    'name'          => 'hehe',
    'custom_fields' => [
        'email' => 'test@example.com',
    ],
]);
$item = (new InvoiceItem())->title('Service 1')->pricePerUnit(2);
$invoice = Invoice::make()
    ->buyer($customer)
    ->addItem($item);

return $invoice->stream();
```

then i got this error 
```
Error
Class 'NumberFormatter' not found (View: /Applications/XAMPP/xamppfiles/htdocs/WORK/af/vendor/laraveldaily/laravel-invoices/resources/views/templates/default.blade.php)
http://af.local/license/create 
```

**Step to get this error**
I use composer to install laravel-invoices using this
`$ composer require laraveldaily/laravel-invoices:^2.0`
then i put this on `config/app.php` at `aliases`
`'Invoice'       => LaravelDaily\Invoices\Facades\Invoice::class,`
then i import the classes to my class
```
.
.
.
use LaravelDaily\Invoices\Invoice;
use LaravelDaily\Invoices\Classes\Buyer;
use LaravelDaily\Invoices\Classes\InvoiceItem;

class LicenseController extends Controller
```
then i put this code at my `create function` for testing only
```
$customer = new Buyer([
    'name'          => 'hehe',
    'custom_fields' => [
        'email' => 'test@example.com',
    ],
]);
$item = (new InvoiceItem())->title('Service 1')->pricePerUnit(2);
$invoice = Invoice::make()
    ->buyer($customer)
    ->addItem($item);

return $invoice->stream();
```

Did i do wrong here? Or is it a bug? 
Appreciate, Thanks

**Comment by mc0de** [comment]
@mar846 this was answered several times, please see https://github.com/LaravelDaily/laravel-invoices/issues?q=is%3Aissue+NumberFormatter+is%3Aclosed
