### ISSUE TITLE
Unsupported operand types: string + float (When I try to get the invoice)

### ISSUE THREAD

**Issue by Ahmant** [LaravelDaily/laravel-invoices#140]
**Describe the bug**
"Unsupported operand types: string + float" error appears when I try to get the invoice

**To Reproduce**
1. Install package
`composer require laraveldaily/laravel-invoices:^2.0`
2. Add the code from the package documentation's example
`

        $customer = new Buyer([
                'name'          => 'John Doe',
                'custom_fields' => [
                        'email' => 'test@example.com',
                ],
        ]);
        
        $item = (new InvoiceItem())->title('Service 1')->pricePerUnit(2);

        $invoice = Invoice::make()
                ->buyer($customer)
                ->discountByPercent(10)
                ->taxRate(15)
                ->shipping(1.99)
                ->addItem($item);

        return $invoice->stream();
`
3. Import necessary classes
4. Go to the corresponding route/URL
5. Error appears

**Expected behavior**
Get an invoice

**Screenshots**
![image](https://user-images.githubusercontent.com/39812462/152689223-8d90f195-7d41-4259-b91e-d1a74ec07780.png)

**Desktop:**
 - OS: Window 11
 - Browser: Tested on Chrome & Edge
 - Laravel Version: 8.82.0
 - PHP: 8.0.12

**Comment by mc0de** [comment]
Did exactly as described on fresh laravel installation, works as expected.

On other hand, as described, error is in dompdf/dompdf package, not in invoices package.

Try running composer update.

**Comment by mc0de** [comment]
Wasn't able to reproduce the issue

**Comment by mc0de** [comment]
no response

**Comment by Ahmant** [comment]
I am really sorry. I've been very busy at work.

I will try to use a different version of "dompdf/dompdf". Also, I will try to use the invoice package on my college device, probably he has the correct version of "dompdf/dompdf"
