### ISSUE TITLE
Paper settings don't take effect

### ISSUE THREAD

**Issue by Gaspertrix** [LaravelDaily/laravel-invoices#142]
**Describe the bug**
Changing paper.size and paper.orientation don't take any effect

**To Reproduce**
1. Edit config/invoice.php
2. Modify paper.size and paper.orientation
3. Clear config cache
4. Generate an invoice

**Expected behavior**
Pdf has the new set size and orientation

**Actual behavior**
Pdf has a4 size and portrait orientation

------------------
https://github.com/LaravelDaily/laravel-invoices/blob/7e972624193e6a03c3e7d8cdbd9c053e82f487ca/src/Invoice.php#L260

setOptions() is not passing any paper setting and I don't find any reference to setPaper() method in the code. I am missing something?

**Comment by dodaydream** [comment]
I have created a pr regarding to this issue https://github.com/LaravelDaily/laravel-invoices/pull/157, think it may fix this.
