### ISSUE TITLE
Pending Amount/ Balance due Amount

### ISSUE THREAD

**Issue by VenomXL** [LaravelDaily/laravel-invoices#144]
[[**Is your feature request related to a problem? Please describe.**
At times customers don't pay the entire amount in one go, due to which there should be a balance due or pending amount feature introduced. In pending_amount feature, invoices will show the paid amount and the pending amount and meanwhile status must automatically get changed to partially paid instead of due or paid.

**Describe the solution you'd like**
In Invoice, a contract function can be introduced named **`pendingAmount()`** or **`balanceDue()`** which will allow users to give balance or allow user's clients to give them a notice for the paid amount and the unpaid remaining amount.
eg:
```
$customer = new Buyer([
            'name'          => 'John Doe',
            'custom_fields' => [
                'email' => 'test@example.com',
            ],
        ]);

        $item = (new InvoiceItem())->title('Service 1')->pricePerUnit(2000);

        $invoice = Invoice::make()
            ->buyer($customer)
            ->discountByPercent(10)
            ->taxRate(15)
            ->shipping(1.99)
            ->pendingAmount(500) //or balanceDue(500) This means client's 500$ is still pending to be paid
            ->addItem($item);

        return $invoice->stream();
```

**Comment by mc0de** [comment]
This is not a feature useful to everyone, and is pretty much edge case on business logic, feel free to extend the class and maybe submit a PR
