### ISSUE TITLE
Discount over discountByPercent

### ISSUE THREAD

**Issue by VenomXL** [LaravelDaily/laravel-invoices#145]
At times clients are demanding especially when they are really close or regular clients. An additional discount amount should be allowed to be applied even after discountByPercent has already been applied to showcase them they are being over valued or over pampered for being a loyal customer.

**Comment by mc0de** [comment]
You can calculate your own discount logic and provide final discount to ->discount() method.

Stacked discounts are not very usual thing business do.

Feel free to submit a PR
