### ISSUE TITLE
touch(): Unable to create file /tmp/log.htm because No such file or directory

### ISSUE THREAD

**Issue by idzulfaqor** [LaravelDaily/laravel-invoices#146]
I just use ->stream() function, but my controller return the Error: touch(): Unable to create file /tmp/log.htm because No such file or directory
![image](https://user-images.githubusercontent.com/62234766/164987175-f75f55ca-dbc1-47c3-86c6-2fdd21c68d2e.png)

**Comment by mc0de** [comment]
https://www.google.com/search?q=touch()%3A+Unable+to+create+file+%2Ftmp%2Flog.htm+because+No+such+file+or+directory

**Comment by idzulfaqor** [comment]
I was searching in google for hours, and no one thread can solve this problem
