### ISSUE TITLE
I want to change paper size of the pdf to 88mm * 276mm

### ISSUE THREAD

**Issue by faizan-glowlogix** [LaravelDaily/laravel-invoices#147]
Hi,

I want to change the paper size to my custom dimensions it is not working. I even tried to change config->invoice.php to A7 but it's not working for that as well. 

Please let me know how can i do it.

Thanks,

**Comment by faizan-glowlogix** [comment]
Also how to remove page breaks. I am using POS printer for printing purposes.

**Comment by mc0de** [comment]
closing as duplicate #142
