### ISSUE TITLE
Class "LaravelDaily\Invoices\Classes\Buyer" not found

### ISSUE THREAD

**Issue by Masumrahmanhasan** [LaravelDaily/laravel-invoices#149]
![image](https://user-images.githubusercontent.com/55694939/165678961-f8c43c7e-6804-4531-b67f-92bc6cd86d91.png)

i have imported the class but it shows an error ..Class "LaravelDaily\Invoices\Classes\Buyer" not found

**Comment by mc0de** [comment]
@Masumrahmanhasan try `composer dump-autoload -o` and https://www.google.com/search?q=laravel+class+not+found

**Comment by Masumrahmanhasan** [comment]
i did that but not working same error
