### ISSUE TITLE
Laravel 6.3.0 -  $style value 5 behavior is not implemented. 

### ISSUE THREAD

**Issue by m4aax16** [LaravelDaily/laravel-invoices#15]
**Describe the bug**

![invoicesErr](https://user-images.githubusercontent.com/50498034/77494870-48b86980-6e47-11ea-9170-2255693a497e.png)

**To Reproduce**
1. `composer require laraveldaily/laravel-invoices`
2. `php artisan invoices:install`
4. Create  InvoiceController, Add Basic Code to show() method

`
..
use LaravelDaily\Invoices\Invoice;
use LaravelDaily\Invoices\Classes\Buyer;
use LaravelDaily\Invoices\Classes\InvoiceItem;

class InvoiceController extends Controller{

public function show(Invoice $invoice)
    {

        

         $customer = new Buyer([
            'name'          => 'John Doe',
            'custom_fields' => [
                'email' => 'test@example.com',
            ],
        ]);

        
    
        $item = (new InvoiceItem())->title('Service 1')->pricePerUnit(2);
    
  

        $invoice = Invoice::make()
            ->buyer($customer)
            ->discountByPercent(10)
            ->taxRate(15)
            ->shipping(1.99)
            ->addItem($item);
    

        return $invoice->stream();
    }

}`

5.  My web.php

`Route::get('/test', 'InvoiceController@show');
`

6. See error

Same error if I put the code to web.php

**Expected behavior**
Fix bug or give solution

**Comment by PovilasKorop** [comment]
@m4aax16 I think the error suggests you the solution: "please install the "intl" extension for full localization capabilities"

**Comment by m4aax16** [comment]
Soloution for Ubuntu 18.04.4 LTS +  Nginx/1.14.0 + PHP 7.3 : "sudo apt-get update" than "sudo apt-get install php7.3-intl"
