### ISSUE TITLE
Pdf that is generated is fine but its print is blur.

### ISSUE THREAD

**Issue by faizan-glowlogix** [LaravelDaily/laravel-invoices#150]
Hi I have created a pdf with this package now the pdf showing in the display is fine but when printing that document fonts get blurred anyone please guide how to solve it?? 

![After Print Image](https://user-images.githubusercontent.com/66687523/165861592-db94e2c2-2863-45f2-81f0-fcdf2c49645a.jpg)
![PDF](https://user-images.githubusercontent.com/66687523/165862048-f1e90799-4cfb-495f-b4eb-e4c943ef65de.png)

**Comment by mc0de** [comment]
@faizan-glowlogix fix your printer
