### ISSUE TITLE
PDF output takes longer to finish if there are images embedded

### ISSUE THREAD

**Issue by thevalo** [LaravelDaily/laravel-invoices#151]
**Describe the bug**
It takes much more time (5.6 sec) to output a PDF that includes an image(s), than the same invoice without an embedded image (1.8 sec).

**To Reproduce**
1. Embed an image using the `<img>` tag
2. Call the `return $invoice->stream();`
3. Count the time

**Expected behavior**
At least process the image faster rather than waiting so long?

**Desktop (please complete the following information):**
 - OS: Win10 x64
 - Browser: Chrome
 - Version: 101.0.4951.54 x64

**Additional context**
I am not sure if this is considered a "bug" at all, or maybe it's a feature request to process images somehow faster? I am not either sure if it has to do with the CPU itself, but the image whether it's 0.15Mb or 1.5Mb, it's the same result - it takes too long to output a result with images embedded in the invoice template.

**Comment by mc0de** [comment]
@thevalo hi, invoices uses dompdf as an underlying pdf rendering engine, try looking up their issues https://github.com/dompdf/dompdf/issues?q=is%3Aissue+is%3Aopen+image+process
