### ISSUE TITLE
TaxRated summary for each item

### ISSUE THREAD

**Issue by iKyzu** [LaravelDaily/laravel-invoices#153]
**Is your feature request related to a problem? Please describe.**
I am trying to find a solution so I can show the sum or the tax rated item for different items.

**Describe the solution you'd like**
If you choosing tax rate for 5 items 20% and 2 items 10%, I want to show this in summary, that total tax amount for tax rate 19% is "total amount for thix tax rate", and next line with the second used tax rate and the sum of that. Each time there is different tax rate for an item the system will show the sum of this tax rate amount that's calculated. Hope it's understandable.

Taxes 20%           "amount"
Taxes 10%           "amount"
Total taxes          "amount"

**Comment by mc0de** [comment]
@iKyzu you can edit invoice template and include that from existing data already

**Comment by iKyzu** [comment]
@mc0de forach inside the template?

**Comment by iKyzu** [comment]
@mc0de I don't seem to be able to make it work. Could you help me with that?

**Comment by mc0de** [comment]
@iKyzu this is not related to package, but seems more like a job for a hiring

no, i'm not able to do free work, and not taking requests

all i can do for you is to open the issue, and maybe someone from the community will be willing to help you

**Comment by LWlook** [comment]
@iKyzu 
I also needed this feature, so I wrote this block.
This will give you all groups of taxes. Hope this helps, feel free to ask if you have questions.

```blade
        @if($invoice->hasItemTax)
            @php
                $tax_groups = $invoice->items->mapToGroups(fn($item) =>
                    [$item->tax_percentage => [$item->price_per_unit * $item->quantity, $item->tax]]
                )->map(fn($item) =>
                    $item->reduce(fn($carry, $item) =>
                        [$carry[0] + $item[0], $carry[1] + $item[1]]
                    , [0,0])
                );
            @endphp
            @foreach($tax_groups as $key => $tax_group)
                <tr>
                    <td>USt. {{ $key }}% von {{$invoice->formatCurrency($tax_group[0])}}</td>
                    <td>
                        {{ $invoice->formatCurrency($tax_group[1]) }}
                    </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td>USt. {{ $invoice->tax_rate }}% von {{$invoice->formatCurrency($invoice->taxable_amount)}}</td>
                <td>
                    {{ $invoice->formatCurrency($invoice->total_taxes) }}
                </td>
            </tr>
        @endif
```
