### ISSUE TITLE
Some features mentioned in the documentation no longer exist

### ISSUE THREAD

**Issue by Stelikas** [LaravelDaily/laravel-invoices#154]
**Describe the bug**
Trying to set custom data to use inside template

**To Reproduce**
1. Try to create invoice
2. Add setCustomData method
3. Error: Undefined method

**Expected behavior**
To be able to set custom data

**Additional context**
I would like to add additional expenses to the invoice which are inside the order, although i can't seem to pass additional data to the invoice.

**Comment by mc0de** [comment]
@Stelikas check package version you are using and update it if necessary

you can extend any of the classes since every property is made public for this purpose to fit your needs

**Comment by Stelikas** [comment]
I can't find in which version setCustomData method existed it's just written in the documentation, anyway, i will surely extend the classes, thanks for the great package!

**Comment by mc0de** [comment]
@Stelikas it is always recommended to update to latest version
