### ISSUE TITLE
PDF Wont Upload in Ubuntu VPS

### ISSUE THREAD

**Issue by mzcoder-hub** [LaravelDaily/laravel-invoices#156]
hi i got a problem with the pdf wont upload in Ubuntu VPS i already use 

`chown -R www-data:www-data /path/to/dir`

already run `php artisan storage:link`

but work in uploading image

i have try the example code to stream but still the same `500 error`

**Comment by koossaayy** [comment]
What are the content of the log file, when you hit the 500 error ?

**Comment by mc0de** [comment]
@mzcoder-hub this package doesn't make any file uploads

closing as unrelated
