### ISSUE TITLE
Undefined type 'LaravelDaily\Invoices\Invoice'.

### ISSUE THREAD

**Issue by mhraihan** [LaravelDaily/laravel-invoices#160]
**Faced Undefined type error**

The invoice package is working fine.
But the vs code editor displayed error.
How can I solve the errors?

**Errors**

1. Undefined type 'LaravelDaily\Invoices\Classes\Buyer'.
2. Undefined type 'LaravelDaily\Invoices\Classes\InvoiceItem'.
3. Undefined type 'LaravelDaily\Invoices\Invoice'.

those errors I've got while working.

thank you

**Comment by mc0de** [comment]
@mhraihan i dunno, we do not use vscode, this is the question of the editor configuration, and not the issue with the package.
