### ISSUE TITLE
Add an option to Use mPDF instead of DomPDF only

### ISSUE THREAD

**Issue by anahdi** [LaravelDaily/laravel-invoices#162]
Hi 

I would like to know if it is possible to Add an option to Use mPDF instead of DomPDF only .
https://github.com/mpdf/mpdf

Thank you

**Comment by mc0de** [comment]
Probably it is possible by overriding render() method, but I'm not sure what other changes you might need.

**Comment by anahdi** [comment]
Thank you @mc0de 

mPDF support RTL .
Dose this mean overriding render() method to mPDF will make laravel Invoices suport Arabic invoices ? 

Thank you
