### ISSUE TITLE
Does not work with UTF-8 encoding (arabic language for example do not appear clearly)

### ISSUE THREAD

**Issue by haniusif** [LaravelDaily/laravel-invoices#167]
<img width="1402" alt="Screenshot 2022-10-25 at 4 20 16 AM" src="https://user-images.githubusercontent.com/11551840/197666854-185707b3-b835-4c20-aae8-8c0984128aa8.png">

**Comment by mc0de** [comment]
@haniusif this is not package problem.

please use appropriate font for arabic language and configure your dompdf

https://stackoverflow.com/questions/25191484/dompdf-doesnt-support-arabic-characters
