### ISSUE TITLE
Wrong behavior when setting totals manually

### ISSUE THREAD

**Issue by jezzdk** [LaravelDaily/laravel-invoices#17]
**Describe the bug**
If I specify total tax manually, the taxable amount and total amount are always calculated automatically, even if I also set them manually.

**To Reproduce**
$invoice->totalTaxes(20);
$invoice->totalAmount(100);
$invoice->taxableAmount(80);

**Expected behavior**
$invoice->taxable_amount should be 80 and $invoice->total_amount should be 100.

**Actual behavior**
$invoice->taxable_amount is 100 and $invoice->total_amount is 120.

**Additional context**
I got to this problem because I'm entering all item prices _including_ tax, and therefore the taxRate() method would induce extra tax to the total.

**Comment by PovilasKorop** [comment]
@jezzdk thanks for the report, our team is currently busy on other projects, but scheduled to review this report, later this week.

**Comment by mc0de** [comment]
@jezzdk 
Hi, taxableAmount() method was a bit misleading and is about to be removed

to solve your problem you should do
`$invoice->totalTaxes(20)->totalAmount(80)`

what is actually happening is:
1. your total amount is 80
2. trying to apply discounts, so there are none, nothing happens
3. applying your defined taxes by rate or fixed amount, so it is fixed 20
4. totalAmount(80) is about to be taxed, so taxable amount is 80, and new total is 100
5. your desired result

**Comment by mc0de** [comment]
@jezzdk we added a fix to skip automatic tax calculation if ->taxableAmount is defined manually

**Comment by mc0de** [comment]
@jezzdk update to v1.3.10
