### ISSUE TITLE
CSS is not applicable

### ISSUE THREAD

**Issue by frenchqwerty** [LaravelDaily/laravel-invoices#170]
**Describe the bug**
Hello, 

I am trying to include tailwindcss inside my PDF template and it's don't work. 

`<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ $invoice->name }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <link rel="stylesheet" href="{{ public_path('dist/css/app.css') }}" />
</head>

<body>
    {{-- Header --}}
    @if($invoice->logo)
        <img src="{{ $invoice->getLogo() }}" alt="logo" height="80">
    @endif

    <div>
        <h1 class="underline">{{ $invoice->name }}</h1>
    </div>

</body>`

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser : Firefox

**Comment by mc0de** [comment]
@frenchqwerty see https://github.com/dompdf/dompdf/issues/1562
