### ISSUE TITLE
The file "/var/www/pterodactyl/storage/app/invoices/" does not exist

### ISSUE THREAD

**Issue by TeamNoxious** [LaravelDaily/laravel-invoices#172]
**Describe the bug**
Upon customer create of new order, order completes but invoice is not generated. Using both stripe and PayPal gateways and neither are creating an invoice.

**To Reproduce**
1. Create an order
2. Upon order complete, click 'View Invoice'
3. Invoice not created. Throws error saying 'The file "/var/www/pterodactyl/storage/app/invoices/" does not exist'

**Expected behavior**
Upon new order initialize, invoice should be created whether paid or not. 

**Screenshots**
![image](https://user-images.githubusercontent.com/93526659/203575845-ec97c0dc-7024-451a-a31c-3d5c5055b0ef.png)

![image](https://user-images.githubusercontent.com/93526659/203575998-98bcfe7e-6efa-4531-b357-aef3e27542b8.png)

![image](https://user-images.githubusercontent.com/93526659/203576142-cf90d835-411c-4672-95c1-24d269c1e920.png)

![image](https://user-images.githubusercontent.com/93526659/203576220-ae4f062a-4f9b-4b8e-b4a1-6dee32692410.png)

![image](https://user-images.githubusercontent.com/93526659/203577186-f9068ba5-4384-42db-b934-a781fdf4370a.png)

**Additional context**
This is Pterodactyl Panel run on Ubuntu 20.04 VIA ProxMox VM. Invoice is neither created in /storage/app/invoices NOR the SQL database (Refer to IMG 5).

**Comment by mc0de** [comment]
@TeamNoxious There's insufficient information. No snippet available how you generate the invoice.
