### ISSUE TITLE
Add option for tax calculation

### ISSUE THREAD

**Issue by jezzdk** [LaravelDaily/laravel-invoices#18]
**Is your feature request related to a problem? Please describe.**
I have opened a bug report https://github.com/LaravelDaily/laravel-invoices/issues/17.

**Describe the solution you'd like**
It would be nice to be able to set if the item prices are including or excluding tax. Currently, when using the taxRate() method it assumes that prices are excluding tax and applies extra tax to the total.

**Comment by mc0de** [comment]
@jezzdk yes and it is intended and isn't related to #17

check on documentation https://github.com/LaravelDaily/laravel-invoices#invoiceitem

you can apply taxes per item individually instead of whole Invoice

```php
$invoice = Invoice::make()
    ->addItems([
        (new InvoiceItem())->title('Service 1')->pricePerUnit(2)->taxByPercent(10),
        (new InvoiceItem())->title('Service 1')->pricePerUnit(2)->tax(10),
    ])
    ->buyer($customer);
```

**Comment by alexcinergy** [comment]
Hello!

taxByPercent() and tax() are both excluding tax. Is it possible to have including tax options as well?

**Comment by mc0de** [comment]
@see #221
