### ISSUE TITLE
SKU to invoice item

### ISSUE THREAD

**Issue by Stelikas** [LaravelDaily/laravel-invoices#185]
It would be great if it was possible to add item SKU.

**Comment by mc0de** [comment]
@Stelikas it is possible to that by extending `InvoiceItem` class and updating your template to display SKU

**Comment by dragonfly4** [comment]
@mc0de I have extended the class with sku & hasSKu options so it stays optional.

Is this something you would merge if I provide a PR?

**Comment by mc0de** [comment]
In short, no. Adding extra fields that aren't "essential" means more stuff to look after, especially since not every invoice requires an SKU. This package is designed to give you a quick starting point for making invoices and lets you tweak it to suit your business needs.
