### ISSUE TITLE
Bootstrap.css not loaded within relative path

### ISSUE THREAD

**Issue by jdrda** [LaravelDaily/laravel-invoices#19]
Having the same problems as https://github.com/LaravelDaily/laravel-invoices/issues/16

I had to change
`<link rel="stylesheet" href="{{ asset('vendor/invoices/bootstrap.min.css') }}">`
to
`<link rel="stylesheet" href="{{ public_path('vendor' . DIRECTORY_SEPARATOR . 'invoices' . DIRECTORY_SEPARATOR . 'bootstrap.min.css') }}">`

At first I found this in Artisan command, so I wanted to send pull request for this code:
`@if(app()->runningInConsole())
            <link rel="stylesheet" href="{{ public_path('vendor' . DIRECTORY_SEPARATOR . 'invoices' . DIRECTORY_SEPARATOR . 'bootstrap.min.css') }}">
        @else
            <link rel="stylesheet" href="{{ asset('vendor/invoices/bootstrap.min.css') }}">
        @endif`
But it also failed with standard no-console requests.

It seems DomPdf includes everything as files only, not requests. If it is related to Laravel version, it seems to me better to include all style inline (e.g. via @include of separate file with Bootstrap css)

Server
====
Laravel 7.3.0
PHP 7.3.1
Apache 2.4.37
OS Windows 7 Pro SP1

Client
====
OS Windows 7 Pro SP1
Google Chrome 80.0.3987.163

**Comment by mc0de** [comment]
make sure you have updated package
actually there is no such line as
`<link rel="stylesheet" href="{{ asset('vendor/invoices/bootstrap.min.css') }}">`

it should be `<link rel="stylesheet" href="{{ asset('/vendor/invoices/bootstrap.min.css') }}">`

add slash before `vendor`
