### ISSUE TITLE
when i want to download pdf i get this thing. does anyone know where is my mistake

### ISSUE THREAD

**Issue by kautsar-design** [LaravelDaily/laravel-invoices#193]
**Screenshots**
![Screenshot 2023-06-07 222157](https://github.com/LaravelDaily/laravel-invoices/assets/57985626/a76d8683-c66f-4f7f-b247-90d4a0fd6cd5)

this is my table layout

    public function up()
    {
        Schema::create('rekamedis', function (Blueprint $table) {
            $table->id();
            $table->string('name')->nullable();
            $table->string('gender');
            $table->date('date_of_birth')->nullable();
            $table->text('address')->nullable();
            $table->integer('weight')->nullable();
            $table->integer('height')->nullable();
            $table->text('complaint')->nullable();
            $table->integer('tension')->nullable()->default(0);
            $table->integer('temperature')->nullable()->default(0);
            $table->string('title');
            $table->foreignId('obat_id')->constrained();
            $table->string('total')->nullable();
            $table->foreignId('ruanginap_id')->constrained();
            $table->string('action')->nullable();
            $table->timestamps();
        });
    }

**Comment by mc0de** [comment]
@kautsar-design before posting new issue please search past issues.

this has been answered several times.

https://github.com/LaravelDaily/laravel-invoices/issues?q=is%3Aissue+NumberFormatter
