### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by xnekv03** [LaravelDaily/laravel-invoices#196]
Hi,
Just want to brainstorm here. Do you think It would be useful adding web interface? 
Login, create supplier, create invoice etc?

**Comment by PovilasKorop** [comment]
@xnekv03 such web interfaces would be very very individual. I can't imagine how you would create an interface that would suit everyone.

Also, for such full invoicing systems, there are packages like InvoiceNinja and others. Some of them paid, because of how much work involved in building them.
