### ISSUE TITLE
Package installation issue.

### ISSUE THREAD

**Issue by Minhazul-Islam18** [LaravelDaily/laravel-invoices#197]
Hey LaravelDaily Team. Take cordial love.
I'm trying to install the package but it's throwing some errors:
```
  Problem 1
    - Root composer.json requires laraveldaily/laravel-invoices 3.0.0 -> satisfiable by laraveldaily/laravel-invoices[3.0.0].
    - laraveldaily/laravel-invoices 3.0.0 requires illuminate/http ^5.5|^6|^7|^8|^9 -> found illuminate/http[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
```

My Environment is:  
  Laravel Version ................................................................................. 10.13.5  
  PHP Version ....................................................................................... 8.2.4  
  Composer Version .................................................................................. 2.5.8  
  Environment ....................................................................................... local  
  Debug Mode ...................................................................................... ENABLED

I need this solution as early as possible! Thanks in advance specially @PovilasKorop .
<img width="659" alt="Screenshot 2023-08-04 210842" src="https://github.com/LaravelDaily/laravel-invoices/assets/85400832/deb8f086-f7c0-48a5-b21b-358a0f174896">

**Comment by PovilasKorop** [comment]
@Minhazul-Islam18 for some reason it tries to install 3.0 and not 3.1 version that supports Laravel 10.

Try more strict:

```
composer require laraveldaily/laravel-invoices:3.1
```

**Comment by Minhazul-Islam18** [comment]
Thanks, It works.
