### ISSUE TITLE
Error simple demo

### ISSUE THREAD

**Issue by wooside** [LaravelDaily/laravel-invoices#2]
**Describe the bug**
Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: Class 'NumberFormatter' not found (View: D:\Dropbox\site\laravel-6\resources\views\vendor\invoices\templates\default.blade.php)

Window 10
Php 7.3.12
Laravel 6.2

** install **
composer require laraveldaily/laravel-invoices

php artisan invoices:install

use LaravelDaily\Invoices\Invoice;
use LaravelDaily\Invoices\Classes\Buyer;
use LaravelDaily\Invoices\Classes\InvoiceItem;

$customer = new Buyer([
    'name'          => 'John Doe',
    'custom_fields' => [
        'email' => 'test@example.com',
    ],
]);

$item = (new InvoiceItem())->title('Service 1')->pricePerUnit(2);

$invoice = Invoice::make()
    ->buyer($customer)
    ->addItem($item);

return $invoice->stream();

**Comment by PovilasKorop** [comment]
@wooside this NumberFormatter class is used to put amount in words.

You just need to enable this extension in `php.ini` by uncommenting this line: 

```
extension=ext/php_intl.dll
```

For more details visit [this Stackoverflow post](https://stackoverflow.com/questions/30554177/fatal-error-class-numberformatter-not-found)

Or, alternatively, just remove that amount to words function in the invoice blade template:

```
{{ trans('invoices::invoice.amount_in_words') }}: {{ $invoice->getTotalAmountInWords() }}
```

**Comment by wooside** [comment]
Thank you
