### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by soft-dot** [LaravelDaily/laravel-invoices#20]
I can see that there are strings to be translated, but i cannot find how to translate the title of "INVOICE".

**Comment by PovilasKorop** [comment]
@soft-dot thanks for the question/reporting, we are busy on other projects but will investigate and reply/fix a bit later, hopefully within this week.

**Comment by mc0de** [comment]
@soft-dot it is passed as a parameter

https://github.com/LaravelDaily/laravel-invoices/blob/master/src/Invoice.php#L144

you can do `$invoice = Invoice::make('Your name')`
or `Invoice::make(__('en.global.your_invoice_tag'))`

**Comment by gamefriend1996** [comment]
Is there a known bug that destroys Laravel's localization?

Only the respective keys from the normal resources/lang folder are displayed on my complete page.

**Comment by nathan-io** [comment]
@gamefriend1996 yes, the issue would be resolved by https://github.com/LaravelDaily/laravel-invoices/pull/179

For now, you can fix by removing the `resources/lang` folder, clear view cache, and `composer du`
