### ISSUE TITLE
Multiple Tax

### ISSUE THREAD

**Issue by SimardRichard** [LaravelDaily/laravel-invoices#203]
I'm from Quebec in Canada and we use two taxes.  I'm wondering if it would be possible to modify the code to name the taxes and program their operation?  With the possibility of using more than one tax?

Here, for example, we have:
GST: 5%
QST: 9.975

Calculation method:

Amount before taxes x (GST rate/100) = GST amount
Amount before tax x (QST rate/100) = QST amount
Amount before tax + GST amount + QST amount = Amount with tax

**Comment by mc0de** [comment]
Yes it is possible. Extend InvoiceItem and Invoice classes, all methods are public intentionally for this purpose.
