### ISSUE TITLE
path to translations is incorrect

### ISSUE THREAD

**Issue by Treggats** [LaravelDaily/laravel-invoices#209]
**Describe the bug**
Due to a non-existent path, the translations are no longer loaded.

**To Reproduce**
Steps to reproduce the behaviour:

use the following in a test, this will currently fail.
```php
self::assertSame('Prijs', __('invoices::invoice.price', locale: 'nl_NL'));
```

**Expected behavior**
The Dutch (and other languages) should be loaded.

**Change which will fix the issue**
https://github.com/LaravelDaily/laravel-invoices/blob/master/src/InvoiceServiceProvider.php#L31
```diff
-$this->loadTranslationsFrom(__DIR__ . '/../resources/lang', 'invoices');
+$this->loadTranslationsFrom(__DIR__ . '/../lang', 'invoices');
```

**Comment by mc0de** [comment]
This is fixed with the new release.
