### ISSUE TITLE
pdf file size

### ISSUE THREAD

**Issue by tjhunkin** [LaravelDaily/laravel-invoices#217]
is it possible to reduce the pdf file size generated?

**Comment by mc0de** [comment]
It depends on your dompdf configuration.

You may try to add `enable_font_subsetting` flag to `config/invoices.php` and see if it helps.

```php
'dompdf_options' => [
        'enable_font_subsetting' => true,
    ],
```

**Comment by tjhunkin-inhance** [comment]
That is way better 1MB to 174kb

**Comment by tjhunkin-inhance** [comment]
Thanks @mc0de
