### ISSUE TITLE
Can I add a Class for Salary Invoice type ?

### ISSUE THREAD

**Issue by renztoygwapo** [LaravelDaily/laravel-invoices#218]
** I understand that we have already an invoice item list however there are case that I will use the invoice as a Salary Invoice, 
Now the only items I need is for overtime pay, no. of days total work, total deductions etc.

Can we able to create a class for Salary Items ?

**Comment by mc0de** [comment]
You can modify your template and extend classes with features you need. All properties are public with intention to easily overwrite and extend functionality.

Please browse previous issues, this has been answered several times.

https://github.com/LaravelDaily/laravel-invoices/issues?q=is%3Aissue+extend
