### ISSUE TITLE
Can't save invoice in the background without the return $invoice->stream(); method.

### ISSUE THREAD

**Issue by planetgigs** [LaravelDaily/laravel-invoices#22]
**Describe the bug**
Saving the invoice without necessarily having to return to browser gives an error. If you omit return `$invoice->stream();` it throws an error.

**To Reproduce**
1. Create the invoice normally up to `...->save('public')` and comment out the `return $invoice->stream();`
2. See error

**Expected behavior**
Save the invoice to disk and continue generating other invoices.

**Comment by ashuooo7** [comment]
This still won't work

**Comment by mc0de** [comment]
@planetgigs what is the error message? can you provide your code sample?
"It throws error" is not very helpful, also, I did test commenting $invoice->stream() and it works as expected, no errors, and controller returned blank page.

![Screenshot from 2020-06-08 09-53-27](https://user-images.githubusercontent.com/8727992/84000805-114d5980-a96e-11ea-809e-dc929fa01b62.png)

Please provide more information.

**Comment by planetgigs** [comment]
`[2020-06-08 08:14:39] local.ERROR: Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: Argument 1 passed to LaravelDaily\Invoices\Invoice::formatCurrency() must be of the type float, null given, called in /var/www/html/soko/storage/framework/views/df13241d8da4a42902c2c4321bde0e3895751265.php on line 266 (View: /var/www/html/soko/resources/views/vendor/invoices/templates/default.blade.php) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Method Illuminate\\View\\View::__toString() must not throw an exception, caught Facade\\Ignition\\Exceptions\\ViewException: Argument 1 passed to LaravelDaily\\Invoices\\Invoice::formatCurrency() must be of the type float, null given, called in /var/www/html/soko/storage/framework/views/df13241d8da4a42902c2c4321bde0e3895751265.php on line 266 (View: /var/www/html/soko/resources/views/vendor/invoices/templates/default.blade.php) at /var/www/html/soko/vendor/laraveldaily/laravel-invoices/src/Invoice.php:243)
[stacktrace]
#0 {main}
"} `

**Comment by mc0de** [comment]
@planetgigs it clearly states that formatCurrency() must be of the type float, null given, probably this is not an issue with package but your modified template
