### ISSUE TITLE
Precalculation

### ISSUE THREAD

**Issue by alexcinergy** [LaravelDaily/laravel-invoices#220]
Hello!

Is it possible to make a precalculation of the invoice before send it to the browser?

I want to use your calculation() method, but once I've use it then when I sending it to the browser I got:

_Exception: Invoice: you must have taxes only on items or only on invoice in file "/vendor/laraveldaily/laravel-invoices/src/Traits/InvoiceHelpers.php on line 356"_

Because there is a check for:
```
if ($item->hasTax() && $this->hasTax()) {
    throw new Exception('Invoice: you must have taxes only on items or only on invoice.');
}
```

Please assist.

**Comment by alexcinergy** [comment]
I have extend your class with 2 extra methods like

Get calculation:
public function prepare()
```
    {
        parent::validate();
        parent::calculate();
    }
```

Reset before stream
```
    public function reset()
    {
        $this->hasItemTax = $this->total_taxes = $this->total_discount = $this->taxable_amount = 0;
    }
```

But not sure am I right

**Comment by mc0de** [comment]
@alexcinergy it is not clear for me what you're trying to do.

What is the real problem are you trying to solve?

Tax exception is for a reason, usually you should be doing one of this:
- Tax all items at once with same rate on the invoice
- Tax every line item seperately

**Comment by mc0de** [comment]
Closing as there is no further explanation provided.

See https://xyproblem.info/
