### ISSUE TITLE
Copy to clipboard from the doc includes a $ sign

### ISSUE THREAD

**Issue by rabol** [LaravelDaily/laravel-invoices#229]
When you try to copy composer or artisan command from the documentation: https://github.com/LaravelDaily/laravel-invoices

it will include the $ signe which makes the command invalid when pasting into your terminal / command prompt

**Comment by ModestasV** [comment]
There are multiple things, as of why this might be needed. For example:

**This indicates that you are expected to run this in the terminal**
You are not alone in noticing this, but it is very common. There is a clear indication as to where things happen. You can read a few discussions like this: https://meta.askubuntu.com/questions/14841/why-do-people-prefix-code-examples-with-dollar-sign

**This indicates if this is a `sudo` or a normal user command**
Another great use case of this - you can quickly spot if you will need sudo or not. If you don't, it will be a `$`, but if you do, it will be `#`

**Improves security**
Just a reminder that you shouldn't copy-paste commands from the internet. https://www.makeuseof.com/why-you-shouldnt-copy-paste-commands-from-internet/#:~:text=However%2C%20you%20should%20be%20aware,commands%20behind%20harmless%2Dlooking%20code.

---

Besides these reasons **why we might have added them**, you are more than welcome to submit a PR to fix this. But for now, we will not change anything. 

Thanks, and happy invoicing!

**Comment by rabol** [comment]
Not sure why you don't want to fix this: just exclude the $ signe and it will work

**Comment by deivydas0** [comment]
@rabol just delete the $ symbol and try to be more polite with people online

**Comment by ModestasV** [comment]
@rabol Sorry, have you read my comment on reasons why?

**Comment by mc0de** [comment]
@rabol just delete the $ symbol and try to be more polite and less insistive with people online
