### ISSUE TITLE
Qusetion: the serial number can be customized, but it never stored

### ISSUE THREAD

**Issue by rabol** [LaravelDaily/laravel-invoices#23]
The serial number can be customized, but it is always 00001 (if the sequence is 1 in the config file)

That means, that all invoice have number AA.00001, or did I miss something

**Comment by PovilasKorop** [comment]
@rabol this package is about creating a SINGLE invoice PDF file, not store the data in the database. So it's on your side - you should build the numbers logic and sequence, and then pass the exact number you need to the exact single invoice you want to generate pdf.
