### ISSUE TITLE
Support for Farsi text

### ISSUE THREAD

**Issue by saeedmi** [LaravelDaily/laravel-invoices#235]
Hello, good time
How can I use Persian text in PDF?
Are there any special settings?
I have attached a sample image
![Screenshot 2024-10-10 094346](https://github.com/user-attachments/assets/39d16e63-7b1f-45ad-851d-54e8aa2f6bb4)

**Comment by mc0de** [comment]
@saeedmi hi, please check dompdf package docs and issues https://github.com/dompdf/dompdf/issues?q=is%3Aissue+fonts
