### ISSUE TITLE
Library not generating invoice on shared hosting - works on localhost

### ISSUE THREAD

**Issue by Greenvold** [LaravelDaily/laravel-invoices#25]
Hello guys,

I am facing pretty frustrating issue. I have developed website which works like a charm locally on my windows pc. Once i cloned the site on my shared hosting - linux the library does not work. 

I created simple job which is dispatched after order is paid and it generates invoice and thats it. When I run php artisan queue:work and dispatch the job following error occures:

[2020-06-15 06:47:19] local.ERROR: Imagick::clone method is deprecated and it's use should be avoided {"exception":"[object] (ErrorException(code: 0): Imagick::clone method is deprecated and it's use should be avoided at /data/6/d/6d7bb24a-b665-46c0-94cc-3d1fa48bc41f/naucma.online/web/Naucma/vendor/dompdf/dompdf/lib/Cpdf.php:4872)

I have found out that based on post [here](https://github.com/mplodowski/dynamicpdf-plugin/issues/55) that Cpdf file has to be modified. That did not help. Only thing that helps is when i delete these lines from the default.blade.php template file

    @if($invoice->logo)
    <img src="{{ $invoice->getLogo() }}" alt="logo" height="100">
    @endif

Also my second bug is that when i press the back button on the after order processing page in the browser which leads me to the url where the job gets dispatched i get Class 'LaravelDaily\Invoices\Classes\Buyer' not found  which his really strange. 

Here is the job code:

`<?php

namespace App\Jobs;

use App\Order;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Storage;
use LaravelDaily\Invoices\Invoice;
use LaravelDaily\Invoices\Classes\Buyer;
use LaravelDaily\Invoices\Classes\InvoiceItem;

class GenerateInvoice implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    private $order;
    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(Order $order)
    {
        $this->order = $order;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        $items = array();

        $customer = new Buyer([
            'name'          => $this->order->user->name,
            'custom_fields' => [
                'email' => $this->order->user->email,
            ],
        ]);

        if (count($this->order->courses) > 0) {
            foreach ($this->order->courses as $course) {
                array_push($items, (new InvoiceItem())->title($course->title . ' - Kurz')->pricePerUnit($course->price / 1.2));
            }
        }

        if (count($this->order->occurences) > 0) {
            foreach ($this->order->occurences as $occurence) {
                array_push($items, (new InvoiceItem())->title($occurence->training->title . ' - Školenie')->pricePerUnit($occurence->training->price / 1.2));
            }
        }

        $invoice = Invoice::make()
            ->name('Faktúra')
            ->series($this->order->id)
            ->buyer($customer)
            ->discountByPercent($this->order->discount)
            ->totalTaxes($this->order->order_net - $this->order->order_gross)
            ->totalAmount($this->order->order_net)
            ->taxableAmount($this->order->order_net - $this->order->order_gross)
            ->addItems($items)
            ->logo(public_path('vendor/invoices/sample-logo.png'))
            ->filename($this->order->id . ' ' . $this->order->user->id);

        $invoice->save('local');
    }
}`

Dont you know what might be wrong please?

**Comment by PovilasKorop** [comment]
@Greenvold hi, it seems like the errors are in your server/implementation and not the package, sorry without proper debugging I can't help. Looking at your code, it seems ok, so don't have an answer for you, need debugging, sorry.

**Comment by mc0de** [comment]
@Greenvold 
1. there is problem or maybe lack of support of features on shared hosting
alternatively you can embed your base64 encoded image directly into src `<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEU...">` this is exactly what this method does

2. hard to tell what problem there is, you can also try alternative methods, so instead of doing `new Buyer` you can try `Invoice::makeParty([your data here])`

also try run job without SerializesModels

**Comment by Greenvold** [comment]
@mc0de  Thank you I managed to solve the first issue by enforcing the img tag with exact path to the image and also the second issue by using your solution.

Indeed there is limitation on my hosting for imagick. I asked the provider and they said there were many issues and bug fixes with this library. Thank you very much.

**Comment by mc0de** [comment]
@Greenvold glad it helped, happy to hear back
