### ISSUE TITLE
Class 'NumberFormatter' not found 

### ISSUE THREAD

**Issue by sprinbleDev** [LaravelDaily/laravel-invoices#26]
**Describe the bug**
I am using laravel/framework (v5.6.39): and PHP 7.3.9.
I am using version ^1.3.8, and when i try to initiate the call to laravel invoices, i get an error saying
`"message": "Class 'NumberFormatter' not found (View: /app/resources/views/vendor/invoices/templates/default.blade.php)",
    "exception": "ErrorException",
    "file": "/app/vendor/laraveldaily/laravel-invoices/src/Traits/CurrencyFormatter.php",
    "line": 152,`

**Expected behavior**
It is supposed to download the generated invoice

**Desktop (please complete the following information):**
 - OS: Catalina
 - Browser Chrome
 - Version latest

**Additional context**

**Comment by PovilasKorop** [comment]
@sprinbleDev https://stackoverflow.com/questions/30554177/fatal-error-class-numberformatter-not-found

**Comment by josegus** [comment]
this is not right, sometimes we use shared hosting with no access to modify php.ini

**Comment by PovilasKorop** [comment]
@josegus I personally don't recommend anyone to use shared hosting for Laravel projects, cause you will run into a lot of limitations like this

**Comment by Isaac009** [comment]
I am using Ubuntu OS, version 20.04 LTS
PHP version: 7.4.3

To resolve the problem, I did the following;
1. On Ubuntu, Debian, and related Linux distributions

`sudo apt-get install php-intl`

To install the extension for the default PHP version. 
For other versions, a variation like `apt-get install php7.3-intl` will choose the correct extension if the version provided is correct.

If you get this error;
_**The GD Graphics Library is for dynamically manipulating images. For Ubuntu, you should install it manually:**_

Do the following;
1. check your php version : ` php -v`

2. Run one of the commands according to your php version
  
PHP5: `sudo apt-get install php5-gd`
PHP7.0: `sudo apt-get install php7.0-gd`
PHP7.1: `sudo apt-get install php7.1-gd`
PHP7.2: `sudo apt-get install php7.2-gd`
PHP7.3: `sudo apt-get install php7.3-gd`
PHP7.4: `sudo apt-get install php7.4-gd`

3. That's all, you can verify that GD support loaded:
`php -i | grep -i gd`

Output should be like this:

GD Support => enabled
GD headers Version => 2.1.1-dev
gd.jpeg_ignore_warning => 0 => 0

4. Restart your apache service :
`sudo service apache2 restart`

Hope this will help you.
Enjoy coding.
