### ISSUE TITLE
Generate many Invoices?

### ISSUE THREAD

**Issue by francisck0** [LaravelDaily/laravel-invoices#29]
**Is your feature request related to a problem? Please describe.**
I'm trying to generate multiple invoices making a query to database and getting many rows/invoices. Then, when I get all the invoices I need, I don't find the way to generate a PDF file with all invoices.

**Describe the solution you'd like**
Create a new method to invocate it for generating many invoices, one by one printed in a only PDF file.

**Comment by PovilasKorop** [comment]
@francisck0 currently not planning this feature, but we would accept a Pull Request if you add it. 
And even if we did plan this feature, it requires not only the package code but also configuration on the server-side, because such PDF will likely take a lot of time and server resources/memory so may bump into max 30 seconds or max memory limits.

**Comment by kpugazh** [comment]
I am hosting the site in Godaddy Shared Server. 
After testing the package locally I uploaded the files to live server. It said Unable to find Class 'LaravelDaily\Invoices\Classes\Buyer' not found

When I try to run php artisan invoices:install.  Error said "There are no commands defined in the "invoices" namespace."

How can I resolve the issues and get the Invoice generated.

**Comment by mc0de** [comment]
@kpugazh please follow official documentation https://github.com/LaravelDaily/laravel-invoices/blob/master/README.md

**Comment by kpugazh** [comment]
> @kpugazh please follow official documentation https://github.com/LaravelDaily/laravel-invoices/blob/master/README.md

I dont have access to run composer. So I uploaded the package.

If I include LaravelDaily\Invoices\InvoiceServiceProvider::class, in config/app.php -> providers, config:cache shows error that the Class is not found.

In aliases I have 'Invoice' => LaravelDaily\Invoices\Facades\Invoice::class,

and in controller, if I put
use Invoice; 

I get error "Class 'LaravelDaily\Invoices\Facades\Invoice' not found"

Thanks

**Comment by mc0de** [comment]
@kpugazh composer is necessary, otherwise you try to "hack" your solution when autoloading classes

https://getcomposer.org/doc/01-basic-usage.md#autoloading

since this is not the issue with the package i can't help you
