### ISSUE TITLE
Indian Rupee Symbol Not Supported

### ISSUE THREAD

**Issue by bkkrishna** [LaravelDaily/laravel-invoices#3]
**Describe the bug**
The Indian Rupee Symbol (₹) does not show up when used, instead '?' symbol appears in the generated PDF.

How do we integrate the symbol?

**Comment by mc0de** [comment]
@bkkrishna just released an update with 1.3.4 version. Now it works out of the box and default template uses included DejaVu Sans font.

After `composer update` run `php artisan invoices:update`.

If you need something more you can find more information on that here at https://github.com/dompdf/dompdf/wiki/UnicodeHowTo.
