### ISSUE TITLE
Custom Templates?

### ISSUE THREAD

**Issue by sprklinginfo** [LaravelDaily/laravel-invoices#30]
thank you for the great package. After installation, I see the default template. In the readme, it claims the 'templates' feature. Does it mean we can add custom templates? how to use the new templates? Thanks!

**Comment by mc0de** [comment]
@sprklinginfo thank you

1. make sure you have published all assets with `php artisan invoices::install`
2. then you can put your templates to `resources/views/vendor/invoices/templates`

for example `resources/views/vendor/invoices/templates/mytemplate.blade.php`

3. and when creating invoice just specify template name
```php
$invoice = Invoice::make()
            ->buyer($customer)
            ->discountByPercent(10)
            ->taxRate(15)
            ->shipping(1.99)
            ->addItem($item)
            ->template('mytemplate');
```

You can lookup in default template `resources/views/vendor/invoices/templates/default.blade.php` how certain things are implemented.

**Comment by sprklinginfo** [comment]
terrific! Many thanks.
