### ISSUE TITLE
Generate the link to saved invoice pdf file

### ISSUE THREAD

**Issue by sprklinginfo** [LaravelDaily/laravel-invoices#31]
Hi,
I tried to use '$link = $invoice->url();' in the example to generate the a link to the saved file. The file is saved under an 'invoices' folder like this:
`->filename('invoices/abc.134343')
->save('local');`

the result of $link is '/storage/invoices/abc.134343.pdf'. when I tried with http://my-host-domain/storage/invoices/abc.134343.pdf but failed.  Comparing my code to the example code, the only difference is that I used '->save('local'), not '->save('public')'. I don't want the file to be saved to the 'public' directory to protect user privacy. I want to show a download link on a user's dashboard if s/he wants to download the invoice pdf file. Is there a way to create the link without saving the file in 'public'?

Many thanks,

**Comment by PovilasKorop** [comment]
@sprklinginfo not sure about your "local" configuration folders, but as far as I understand, if you don't save file in public, then there can be no direct link to it at all, because it's not public. And that's not about our package, that's how Laravel filesystem works.

**Comment by sprklinginfo** [comment]
here is the 'local' disk on my filesystems.php file:
`
 'local' => [
            'driver' => 'local',
            'root' => storage_path('app')
]
`

**Comment by PovilasKorop** [comment]
@sprklinginfo yes so you can't have a direct link to storage/app files, they're not public, for that specific reason of security.

Public direct link is insecure, by definition.

**Comment by mc0de** [comment]
@sprklinginfo make your own Controller to serve pdf files to logged in users, this way you can have pdf files secured

https://medium.com/@allalmohamedlamine/how-to-serve-images-and-files-privatly-in-laravel-5-7-a4b469f0f706
