### ISSUE TITLE
 'discount' value is incorrect if new InvoiceItem with 'discountByPercent()' and subTotalPrice()' together

### ISSUE THREAD

**Issue by sprklinginfo** [LaravelDaily/laravel-invoices#32]
**Describe the bug**
InvoiceItem 'discount' value is incorrect if new InvoiceItem is initialized with 'discountByPercent()' and subTotalPrice()' together.

**To Reproduce**
`$item = (new InvoiceItem())->title('Service 1')->pricePerUnit(66.81)->quantity(1)->discountByPercent(8)->subTotalPrice('61.47');`
In above code, without setting the sub_total_price, the value for 'discount' property is 5.34 which is correct.
if using 'subTotalPrice' method to set the sub_total_price as well, the value for 'discount' is 8 instead. 

From instruction, we should be able to use 'subTotalPrice' method on InvoiceItem?
subTotalPrice(float) - If not provided calculates itself

**Expected behavior**
the value of 'discount' should be calculated correctly no matter whether 'subTotalPrice()' is called or not.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - Browser [chrome]
 - Version [84]

**Additional context**

**Comment by mc0de** [comment]
@sprklinginfo then you should not use subTotalPrice(), because it is meant to override calculation, so behaviour is expected.
