### ISSUE TITLE
Css and Style not working

### ISSUE THREAD

**Issue by HADES-TECH** [LaravelDaily/laravel-invoices#33]
This really is an amazing Package and eases many things in invoice generation. But I am having an issue:
When I try to Stream or download the PDF it doesn't work and web page just keeps on loading. But when I comment out the CSS link and Style, it downloads.

**Comment by sprklinginfo** [comment]
Can't remember where I saw it. changing the style line as below solved the issue. don't know why.
from:
'<link rel="stylesheet" href="{{ asset('/vendor/invoices/bootstrap.min.css') }}">
to:
`<link rel="stylesheet" href="{{ public_path('/vendor/invoices/bootstrap.min.css') }}">`

**Comment by PovilasKorop** [comment]
@HADES-TECH try that solution by @sprklinginfo and tell us if it works, so we could close the issue

**Comment by HADES-TECH** [comment]
By changing asset to public path, blade view is not detecting the css link. But it works for me, Thanks.

**Comment by HADES-TECH** [comment]
Also, Is this the correct way to save file in desired folder?
` ->save(public_path('uploads/release'));`
It gives me this exception: InvalidArgumentException
Disk [C:\Users\KN7\Desktop\Living Fashions\Laravel Projects\lfims\public\uploads/release] does not have a configured driver.

**Comment by mc0de** [comment]
@HADES-TECH define your disk in `config/filesystems.php`

it looks like this
```
    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
...
```
then use for example `->save('public')` or `->save('yourdisk')`
