### ISSUE TITLE
How to store PDF in dynamically generated folder?

### ISSUE THREAD

**Issue by HADES-TECH** [LaravelDaily/laravel-invoices#35]
Hi, I am trying to store my PDF in a folder which is dynamically generated each time the function is called. 

Here is my Controller:

`->save('pdf_public'.'/'.$shipment_id.'/');`

I did the same with MaatWebsite Excel package, and it was working, but in this case, it shows this exception:

Disk [pdf_public/waq1/] does not have a configured driver. 

My filesystems.php code:
```
'pdf_public' => [
            'driver' => 'local',
            'root' => public_path('uploads/release/'),
            'url' => env('APP_URL'),
            'visibility' => 'public',
        ],
```
What am trying to achieve is that every time the function is called, the pdf must be stored in the following location: 

pdf_public/$shipment_id, whereas $shipment_id is different everytime.

**Comment by PovilasKorop** [comment]
@HADES-TECH we don't have that feature, our `save()` function accepts DISK but not folder: https://github.com/LaravelDaily/laravel-invoices/blob/master/src/Traits/SavesFiles.php

But if you want to create a specific `saveToFolder()` method, we would accept a Pull Request for this.

**Comment by HADES-TECH** [comment]
Will that solve my isuue? Because the folder will be created dynamically each time the function is called.
