### ISSUE TITLE
Invoice incorrectly rendered and takes a long time with php artisan serve

### ISSUE THREAD

**Issue by LemarinelNet** [LaravelDaily/laravel-invoices#36]
I know that this bug will be hard to resolve, perhaps impossible , but, for the records...

It took me a long time to pinpoint my issue: In fact, the invoice I tried to render (even the demo one), took a minute to render. Every time, a single minute ! Not a second more, not a second less !
And even more, the rendering was completely different from the demo PDF. It was clear that the CSS file did not seem to be used.
So, I tried to remove the CSS link from the template, and boom. Almost instant rendering !

It was clear to me that the CSS file could not be retrieved (hence the 60s timeout and wrong rendering).
After thinking a minute, I thought that it was clear : php embedded server CANNOT serve more than ONE connection at once. And this connection was used by the call to the invoice, so when the invoice asked to the embedded server another connection to serve the CSS file, it failed!

My workaround was to setup an Apache or Nginx server to serve my project... overkill and I always managed to do without.... but....

So, perhaps instead of getting the CSS file from HTTP, we could get it directly from the disk ? Would it work with DomPDF ?
It would also fail for embedded images I think (but I haven't tried), but can we also load them from disk directly ??

**Comment by PovilasKorop** [comment]
@LemarinelNet as I see in default template, it loads from the same URL, so same project, not from some `http://something`: https://github.com/LaravelDaily/laravel-invoices/blob/18c02fcebccc29b5a2cf44b3dd9d0e3cbe7c927e/resources/views/templates/default.blade.php#L7

```
<link rel="stylesheet" href="{{ asset('/vendor/invoices/bootstrap.min.css') }}">
```

So I'm not sure what we can do here to load CSS without a connection, if you have any ideas please test and make a Pull Request.

To be very honest, personally I have never created any more serious projects on `php artisan serve` because it doesn't represent a real server setup in production environment, for me it's just a quick way to test things but I wouldn't use it for testing anything more complex or more significant. So I don't think we need to spend time on fixing this, unless you have a solution that we would accept.

**Comment by Kayla-Lamp** [comment]
I had this issue as well, and resolved it by replacing `<link rel="stylesheet" href="{{ asset('/vendor/invoices/bootstrap.min.css') }}">`
 with `<link rel="stylesheet" href="{{ public_path('/vendor/invoices/bootstrap.min.css') }}">`
Hopefully this helps!

**Comment by Kayla-Lamp** [comment]
I had a similar issue and resolved it by changing
`<link rel="stylesheet" href="{{ asset('/vendor/invoices/bootstrap.min.css') }}">`
to
`<link rel="stylesheet" href="{{ public_path('/vendor/invoices/bootstrap.min.css') }}">`

Hopefully this helps in your situation as well.

**Comment by LemarinelNet** [comment]
> To be very honest, personally I have never created any more serious projects on `php artisan serve` because it doesn't represent a real server setup

Yes, I know that it doesn't represent a real server setup, but until now, it did responded to 99% of my development needs. And I know that if the performance is satisfying in this dev' setup, it will be even better on a real production server. At the opposite, if the perf's aren't good, it's a good metric to show that something's going wrong, and I want to fix it before going to prod !



> Hopefully this helps in your situation as well.

Sure it will, and it also should be used this way on images ! 
This effectively replaces http://.... calls to /home/to/your/project/public/path files... and since you say that it works, I'm sure it should work 100% of the time !
I think this chance can be merge on the source code : 
It seems to me even a best practice : why should we load a local file with http://path.to.the.website where we could load it directly from the filesystem ;)

**Comment by mc0de** [comment]
we will look into that
