### ISSUE TITLE
Bootstrap can't render

### ISSUE THREAD

**Issue by vinay-kaklotar** [LaravelDaily/laravel-invoices#39]
When I use **return view** at that time it displayed perfectly. But when **stream()** it was not working

**Comment by mc0de** [comment]
@vinay-kaklotar can you describe exactly what happens? and what environment you use etc.? maybe have part of your code?
are you running nginx or artisan serve?

**Comment by vinay-kaklotar** [comment]
![image](https://user-images.githubusercontent.com/48858481/92729524-16b4a880-f390-11ea-81fa-23642c875ee3.png)
I've 

![image](https://user-images.githubusercontent.com/48858481/92729638-3f3ca280-f390-11ea-88c2-c43ba57c06d6.png)

![image](https://user-images.githubusercontent.com/48858481/92729678-5085af00-f390-11ea-8ac6-bcb05ea4f315.png)

Here, the view and code of the controller in the above images

**Comment by mc0de** [comment]
@vinay-kaklotar are you sure you have run `php artisan invoices:install` like specified in instructions?

https://github.com/LaravelDaily/laravel-invoices#installation

**Comment by maciej2303** [comment]
css dont work

**Comment by PovilasKorop** [comment]
@maciej2303 yes we noticed something wrong with external CSS, it's on the list to fix this week. Possibly we need to change PDF generation engine.

**Comment by annejan89** [comment]
Please fix this!
