### ISSUE TITLE
"Ct." still shows irrespective of setting in currencyFraction(string)

### ISSUE THREAD

**Issue by theo-1** [LaravelDaily/laravel-invoices#41]
**Describe the bug**
Amount in words still ends with "ct." Where else is this setting meant to display?

**To Reproduce**
Set 
->currencyFraction("anything")

**Expected behavior**
Expect it to show the currency fraction word or its abbreviation.

**Screenshots**
Not necessary

**Desktop (please complete the following information):**
All

**Comment by Marius-K** [comment]
Hello @theo-1 

I couldn't reproduce this bug, it works for me. Can you provide more information to reproduce it?

**Comment by c-myers1** [comment]
Since I was just trying our the library, all I did was follow the install instructions, modify the first example to have a a custom currency fraction and I still got the ct. Can you share your generated pdf so I'm sure we're talking about the same thing?

**Comment by Marius-K** [comment]
Code for invoice generation taken from [example of advanced usage](https://github.com/LaravelDaily/laravel-invoices#advanced-usage):
![Code](https://user-images.githubusercontent.com/35399830/94251510-4c7a9500-ff2b-11ea-8b69-af4e485a7f38.png)

PDF:
[Roosevelt Lloyd Ashley Medina.pdf](https://github.com/LaravelDaily/laravel-invoices/files/5281885/Roosevelt.Lloyd.Ashley.Medina.pdf)
