### ISSUE TITLE
can this add new return method

### ISSUE THREAD

**Issue by jouniikaheimo** [LaravelDaily/laravel-invoices#44]
Can this add one return method path() now can stream and url.. sometime is relevant use the path ?

**Comment by PovilasKorop** [comment]
@jouniikaheimo sorry I didn't understand, can you give an example or rephrase your question? Stream, URL and path? Didn't understand exactly what you mean.

**Comment by jouniikaheimo** [comment]
@PovilasKorop   i meant couldn't find an option to get the relative path to pdf file. i only found method save(), url() and Stream().. however, in some cases, the use of a relative path is useful

**Comment by PovilasKorop** [comment]
@jouniikaheimo I don't think we have that feature, but I'm happy to accept it as a Pull Request if you make it.

**Comment by jouniikaheimo** [comment]
@PovilasKorop i do it to night
