### ISSUE TITLE
Send PDF as attachment in emails

### ISSUE THREAD

**Issue by InfoSecRavindra** [LaravelDaily/laravel-invoices#46]
**Is your feature request related to a problem? Please describe.**
Hi, I want to send invoice as attachment in email but don't want to save locally, can I do that?

**Comment by PovilasKorop** [comment]
@InfoSecRavindra we don't have such feature inside the package, but you can save locally, send email and then delete the file after sending. This is outside of this package scope.

**Comment by stmn** [comment]
For future seekers:
You don't need to save file to send. Content is easly accessible from stream:

> $invoice->stream()->getContent()

**Comment by itsrexb** [comment]
> For future seekers: You don't need to save file to send. Content is easly accessible from stream:
> 
> > $pdfContent = $invoice->stream()->getContent()
> > $this->attachData($pdfContent, 'yourpdf.pdf', [
                    'mime' => 'application/pdf',
                ]);
