### ISSUE TITLE
Template/ Bootstrap doesn't work

### ISSUE THREAD

**Issue by sprklinginfo** [LaravelDaily/laravel-invoices#47]
**Describe the bug**
On Laravel 7.28. After the 'composer update' the invoice package is on 1.3.11. then the template/bootstrap doesn't work anymore. I tried 'php artisan invoices:update' as instructed, but the template still doesn't work. any suggestion? do I need to update to version 2 even I am using Laravel 7? thanks.

**Comment by mc0de** [comment]
@sprklinginfo you can update to v2, it works on laravel 7 too.

1.3.11 will no longer receive updates
