### ISSUE TITLE
Unable to locate any files from public folder

### ISSUE THREAD

**Issue by Greenvold** [LaravelDaily/laravel-invoices#48]
Hi,

I am facing issue with using this package with laravel nuxt project. When i generate the invoice it runs smoothly however i dont see any images, css in the pdf. They cannot be found. 

![image](https://user-images.githubusercontent.com/56951790/97112708-183ef380-16e6-11eb-9317-a91c5d39be15.png)

But all of the used css and images within the template are accessible via these links for example: 

http://localhost:800/vendor/invoices/bootstrap.min.css

This is the way how css is included:
`
    <link rel="stylesheet" href="{{ asset('/vendor/invoices/bootstrap.min.css') }}">`
The asset method is giving the same url as above. I checked via tinker. 

And this is the way the image is used:
` <img src="{{ public_path('/vendor/invoices/logo.png')}}" width="20%" alt="">`

Do you know what might be the issue? I was googling a lot and found something about settings in dom PDF

$dompdf->set_option('isRemoteEnabled', true);  

But i do not know if that might do the trick or how to set it up.

Thank you

**Comment by ikkebra** [comment]
If you are running this from a sub-folder and not from the root folder, you will need to remove the leading '/' from the asset/public_path

**Comment by Greenvold** [comment]
`  <link rel="stylesheet" href="{{ public_path('vendor/invoices/bootstrap.min.css') }}">`

I have also tried that however didnt work. Only think that work for me for now is if i copy paste the whole bootstrap into style tag and trasnform image into base64. But it's not the best solution.
