### ISSUE TITLE
Total Discount text

### ISSUE THREAD

**Issue by robov** [LaravelDaily/laravel-invoices#49]
Is there a way to specify the discount text to be dynamically ?
Ie :
Total                     20
Coupon (50%off)    5
Total amount        15

Or how else can I communicate WHY the discount is applied

**Comment by robov** [comment]
I think the most flexible way is to be able to pass custom data to the template

**Comment by PovilasKorop** [comment]
@robov I don't think we have this as a feature. But if you build it, I'm happy to accept a Pull request.

**Comment by mc0de** [comment]
@robov you can modify template as you like, also you can have custom data via setCustomData() and getCustomData() methods
