### ISSUE TITLE
Multiple Custom Invoice templates

### ISSUE THREAD

**Issue by arvindkumarbadwal** [LaravelDaily/laravel-invoices#54]
Hi,

Currently, Laravel Invoices has only one template.
Is there any way to support for multiple other custom invoice templates?

Allow other people or developers to create there own custom templates or use from a set of templates.

**Comment by mc0de** [comment]
@arvindkumarbadwal if you have read the readme it has only one built-in template, but allready supports multiple of them.

you can choose your template via template() method. place them where your default one is.
