### ISSUE TITLE
Choosing the language for the total amount in words

### ISSUE THREAD

**Issue by IvalinV** [LaravelDaily/laravel-invoices#56]
It will be helpful if you can specify  the language for the `$formatter = new NumberFormatter('en', NumberFormatter::SPELLOUT);` in `CurrencyFormatter.php` so you will be able to provide a different language than English for the amount in words.

**Comment by mc0de** [comment]
@IvalinV it is allready there, update package

use second parameter as locale

https://github.com/LaravelDaily/laravel-invoices/commit/8d4a53a164421640eeeb205ea2f5922f009eebc3

**Comment by IvalinV** [comment]
@mc0de I didn't look for release before posting this, sorry about that. 

You can choose the locale, but the return is still hardcoded
 ` return sprintf(
            '%s %s and %s %s',
            ucfirst($integer_value),
            strtoupper($this->currency_code),
            $fraction_value,
            $this->currency_fraction
 );`
If you leave it that way the end result will be: `Сумата словом: двеста двадесет и три лева and шестдесет и шест ст. `

**Comment by mc0de** [comment]
@IvalinV you can extend class and override methods as you like it, all class attributes and methods are public

**Comment by IvalinV** [comment]
@mc0de I certainly will.
