### ISSUE TITLE
Not a bug but a support question: How dows page breaks work?

### ISSUE THREAD

**Issue by parijke** [LaravelDaily/laravel-invoices#57]
I looked into the blade file but I can't seem to detect how the page breaks are handled. I would like to make shure that no column headers are shown on empty rows like this:

Instead, if pagebreak happens, at least one row of the prevoius rows should be shifted to the next page, otherwise the column headers don't make sense? See picture what I mean

![image](https://user-images.githubusercontent.com/7671998/101624927-fe017080-3a1a-11eb-924c-ba0d5337948e.png)

**Comment by mc0de** [comment]
@parijke hi, we are using https://github.com/barryvdh/laravel-dompdf which is PDF wrapper for laravel of https://github.com/dompdf/dompdf package and Invoices package doesn't handle page breaks. Maybe answer lies somewhere here.
