### ISSUE TITLE
Invoice looks different like on example pdf

### ISSUE THREAD

**Issue by vaskomichal** [LaravelDaily/laravel-invoices#58]
**Describe the bug**
I installed version laravel-invoices:^1.3. Copy and paste a basic example from GitHub to the controller. My invoice looks different from the basic example invoce.pdf

What I did incorrectly?
<img width="844" alt="Screenshot 2020-12-20 at 16 02 35" src="https://user-images.githubusercontent.com/12744025/102716545-cfb64780-42dc-11eb-809d-1454c4d10011.png">

Thanks

**Comment by mc0de** [comment]
@vaskomichal v1.3 is no longer supported, please update to v2
