### ISSUE TITLE
pdf isn't showing CSS styles

### ISSUE THREAD

**Issue by walaaalmousa97** [LaravelDaily/laravel-invoices#59]
![image](https://user-images.githubusercontent.com/74488917/103172316-46ae8b80-485b-11eb-9aba-bba0825e2763.png)
this is what the pdf look like on print , it used to be fine but on day I Opened it looked like this 
any  Idea Why ??

**Comment by ModestasV** [comment]
Hey, maybe it's related to one of those issues:

https://github.com/LaravelDaily/laravel-invoices/issues/58

https://github.com/LaravelDaily/laravel-invoices/issues/51

Please make sure you are using newest version
