### ISSUE TITLE
Please introduce the shipping charge

### ISSUE THREAD

**Issue by Xatta-Trone** [LaravelDaily/laravel-invoices#6]
This package is awesome for invoices. But when I looked for the **shipping charge** option. I found that it is not there. 
Please kindly add this feature.

**Comment by PovilasKorop** [comment]
@Xatta-Trone please give more information on how would that look/work, we may add it. But only later in 2020, currently very busy.

Or we are accepting pull requests, too.

**Comment by mc0de** [comment]
closing.

no reply in 14 days.

**Comment by osuagwu** [comment]
> @Xatta-Trone please give more information on how would that look/work, we may add it. But only later in 2020, currently very busy.
> Or we are accepting pull requests, too.

Just like you have tax, you need to have shipping, else the package will to be useful for items with shipping charge

**Comment by PovilasKorop** [comment]
@osuagwu ok reopening the issue, but realistically will be able to build it in the middle of February, currently busy with other projects.

If you're in a hurry, you may build it yourself and send us a Pull Request.

**Comment by khalidmaquilang** [comment]
Any update on this?

**Comment by PovilasKorop** [comment]
@khalidmaquilang no the issue was closed as the author didn't provide their own pull request for this feature

**Comment by khalidmaquilang** [comment]
oh i see.. i was hoping that this package supports tax for shipping..
