### ISSUE TITLE
Installation failed for Laravel v 7.30.1

### ISSUE THREAD

**Issue by asimshazad** [LaravelDaily/laravel-invoices#63]
I am trying to install this package on Laravel v7.30.1 and my PHP version is 7.4.3.
I have attached the screenshot below which I got during installation. can you please advise me on this?

![Selection_033](https://user-images.githubusercontent.com/14991207/105672667-9fc71900-5f06-11eb-9ebb-476bc55fe248.png)

This is my composer.json
    "require": {
        "php": "^7.2.5|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^6.3.1|^7.0.1",
        "laravel/cashier": "^12.5",
        "laravel/framework": "^7.30.1",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^2.1",
        "spatie/laravel-stripe-webhooks": "^2.5",
        "stripe/stripe-php": "^7.62",
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.5",
        "facade/ignition": "^2.0",
        "fakerphp/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.3",
        "phpunit/phpunit": "^8.5.8|^9.3.3"
    },

**Comment by PovilasKorop** [comment]
@asimshazad hard to tell from this message. In our case, we don't require Laravel at all, whether it's 7.30 version or higher/lower, see our composer.json: https://github.com/LaravelDaily/laravel-invoices/blob/master/composer.json

So it should work, in my opinion. Maybe some other dependencies are conflicting, and not our package? Just guessing, there's nothing really helpful in the composer error message itself.

**Comment by asimshazad** [comment]
Thank you @PovilasKorop for the quick reply.
On digging deeper I found that there was version conflict with "barryvdh/laravel-dompdf" and downgraded it 0.8.7 and it works fine.
