### ISSUE TITLE
Issues with PHP 8

### ISSUE THREAD

**Issue by MarekMaz** [LaravelDaily/laravel-invoices#64]
After upgrading to PHP 8 I am getting the following error: 

ErrorException · Invalid characters passed for attempted conversion, these have been ignored. 

The error is thrown while crating a pdf version of an invoice. it's related to outdated version on barryvdh/laravel-dompdf (that doesn't support php 8) used currently in the library. The library should be updated to the latest 0.9 version probably.

**Comment by mc0de** [comment]
@MarekMaz just updated, might take few minutes while composer updates repo, make it is v2.0.6

**Comment by MarekMaz** [comment]
That was quick! Thank you
