### ISSUE TITLE
Invoice items

### ISSUE THREAD

**Issue by shikky-boy** [LaravelDaily/laravel-invoices#68]
Please I am having a challenge displaying an array of data from the database into the InvoiceItem. It always displays only one row from the database, but I want to display all table rows. Below is the code I wrote in my sales invoice controller. Thanks.

 foreach ($salesInvoiceLines as $invoiceLines) {
          
            $items = [
                (new InvoiceItem())->title($invoiceLines->PROD_Name)->pricePerUnit($invoiceLines->SIL_UnitPrice)- 
                  >quantity($invoiceLines->SIL_Quantity),
   
            ];

**Comment by mc0de** [comment]
@shikky-boy this is exactly what you're doing with this line of code

https://www.google.com/search?q=php+loop

**Comment by mc0de** [comment]
@shikky-boy it should be
```php
$items[] = (new InvoiceItem())->title($invoiceLines->PROD_Name)->pricePerUnit($invoiceLines->SIL_UnitPrice)- 
              >quantity($invoiceLines->SIL_Quantity);
```

**Comment by shikky-boy** [comment]
> @shikky-boy this is exactly what you're doing with this line of code
> 
> https://www.google.com/search?q=php+loop

Well understood sir

**Comment by shikky-boy** [comment]
> @shikky-boy it should be
> 
> ```
> $items[] = (new InvoiceItem())->title($invoiceLines->PROD_Name)->pricePerUnit($invoiceLines->SIL_UnitPrice)- 
>               >quantity($invoiceLines->SIL_Quantity);
> ```

thank you so much. hoping there's another package similar to this, that can help me to generate sales and inventory reports including charts and graphs. Anyway, thanks again.
