### ISSUE TITLE
Class "NumberFormatter" not found 

### ISSUE THREAD

**Issue by Kennexcorp** [LaravelDaily/laravel-invoices#69]
How can I resolve the error above when trying to generate a receipt using laravel 8 framework

**Comment by cverster** [comment]
Hi there, assuming that you've fixed this, but you need to install the php intl extension.
Go to your php.ini file and uncomment the following line:

extension=intl

**Comment by UltraSoftware0** [comment]
I am facing the same problem tried this way but it did not work
