### ISSUE TITLE
Required parameter $dompdf follows optional parameter $paper when using ->stream()

### ISSUE THREAD

**Issue by DanielvdSpoel** [LaravelDaily/laravel-invoices#70]
**Describe the bug**
When I try to generate a invoice PDF using the following code:
`public function handle(Order $order): Invoice
    {
        $customer = new Buyer([
            'name'          => $order->first_name . " " . $order->last_name,
            'custom_fields' => [
                'email' => $order->email,
            ],
        ]);

        $item = (new InvoiceItem())->title('Verhuur ' . $order->boat->name . " op " . $order->date . " van " .  $order->timeslot->time_end . " tot " . $order->timeslot->time_end)->pricePerUnit($order->timeslot->price);

        $invoice = Invoice::make()
            ->buyer($customer)
            ->addItem($item);

return $invoice->stream()

    }`

**To Reproduce**
1. esecute the code

**Expected behavior**
Returns a view with the invoice

**Screenshots**
https://gyazo.com/31b6d5142f7ac270bb7cd0baf2e3c752

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser All
 - Version N.A.

**Additional context**
None

**Comment by mc0de** [comment]
very vague description, can't help with provided information
