### ISSUE TITLE
Generated PDF layout issue

### ISSUE THREAD

**Issue by WebMedic-X** [LaravelDaily/laravel-invoices#74]
Hi,

Thanks for creating this package, it will save us a lot of time to issue invoices easily.

While trying out the example code, the outputted PDF here isn't good.

https://secure.webmedic.com/Nds3xG

Notice how the contents are using a small portion of the file vs how it should be (full layout)

Code:

` $client = new Party([
            'name'          => 'Company',
            'custom_fields' => [
                'hello' => 'test',
            ],
        ]);

        $customer = new Party([
            'name'          => 'Ashley Medina',
            'address'       => 'The Green Street 12',
            'code'          => '#22663214',
            'custom_fields' => [
                'order number' => '> 654321 <',
            ],
        ]);

        $items = [
            (new InvoiceItem())->title('Sample')->pricePerUnit(10),
        ];

        $notes = [
            'your multiline',
            'additional notes',
            'in regards of delivery or something else',
        ];
        $notes = implode("<br>", $notes);

        $invoice = Invoice::make('receipt')
            ->series('BIG')
            ->sequence(667)
            ->serialNumberFormat('{SEQUENCE}/{SERIES}')
            ->seller($client)
            ->buyer($customer)
            ->date(now()->subWeeks(3))
            ->dateFormat('m/d/Y')
            ->payUntilDays(14)
            ->currencySymbol('RM')
            ->currencyCode('MYR')
            ->currencyFormat('{SYMBOL}{VALUE}')
            ->currencyThousandsSeparator('.')
            ->currencyDecimalPoint(',')
            ->filename($client->name . ' ' . $customer->name)
            ->addItems($items)
            ->notes($notes)
            ->logo(public_path('vendor/invoices/sample-logo.png'))
            // You can additionally save generated invoice to configured disk
            ->save('public');

        $link = $invoice->url();`

Thank you

**Comment by mc0de** [comment]
@WebMedic-X 

it seems there's a problem with assets, are you sure you ran `$ php artisan invoices:install` after composer install?

**Comment by WebMedic-X** [comment]
Hi @mc0de 

Yes sure and did an update on the templates as well as per instructions

I am using Laravel 6.x though is that a problem? and installed the relevant Laravel Invoices version for it

Thanks

**Comment by mc0de** [comment]
@WebMedic-X unfortunately v1 is no longer supported nor maintained, you can try to make custom template

other thing what i would suggest is to take blade template used to generate pdf from v2, im not sure it is compatible 100%, but few small changes might be worth it would save time either

copy from v2 `resources/views/vendor/invoices/templates/default.blade.php` to `resources/views/vendor/invoices/templates/my-template.blade.php`

and when calling invoice add `->template('my-template')`

yes overall a lot things changed also on external libraries than were used by and we had fixed various similar issues, best case scenario would be upgrade application to newest laravel version and use package v2, but i understand that this is not always possible

**Comment by etchkay** [comment]
Hey,
I guess you've found a solution for it by now, but any one else looking for a solution, this one fixed mine:
[Invoice style not applied](https://github.com/LaravelDaily/laravel-invoices/issues/51)
I had the same issue using laravel 7.30 with v1 of laravel invoices.
it works like a charm now
