### ISSUE TITLE
problem with Arabic letters !

### ISSUE THREAD

**Issue by andronady** [LaravelDaily/laravel-invoices#78]
I need to print Arabic words but I can't 

![Screen Shot 2021-04-03 at 6 47 13 PM](https://user-images.githubusercontent.com/24689606/113485282-04759580-94ad-11eb-92c8-c9d64dd88a8e.png)

**Comment by mc0de** [comment]
Sorry, but there's no additional information how can I help you with that. I don't understand Arabic and cannot tell you what is wrong and what expected results are.

**Comment by mc0de** [comment]
Please provide more information and how I could test that or some guidelines.

**Comment by andronady** [comment]
I see the Package not supporting Arabic language ,  the characters appear separated not as complete words for example this Arabic word must be ' مرحبا' . but when I print it throw the package it appear ' ا ب ح ر م '

**Comment by andronady** [comment]
@mc0de ?

**Comment by mc0de** [comment]
@andronady we depend on https://github.com/barryvdh/laravel-dompdf/ package for generating pdf files. So it is not for us to decide if we can support RTL languages.

So it is not a problem with our package.

Maybe there's more information how to solve that in Dompdf issues.

https://github.com/barryvdh/laravel-dompdf/issues/368
https://github.com/barryvdh/laravel-dompdf/issues/471

**Comment by Professor93M** [comment]
I've same issue with the original one, the arabic words not shown correctly.

please any advice?

**Comment by 200-0K** [comment]
For anyone asking, do this:

**Install MPdf package**:
   ```bash
   composer require carlos-meneses/laravel-mpdf
   ```

**Create a Custom Invoice Class**: Extend and override the `render()` method in a new class.
   ```php
   <?php

   namespace App\Classes\Invoice;

   use Mccarlosen\LaravelMpdf\Facades\LaravelMpdf as PDF;
   use LaravelDaily\Invoices\Invoice as LaravelInvoice;

   class Invoice extends LaravelInvoice
   {
       public function __construct()
       {
           parent::__construct();
       }

       public function render()
       {
           if ($this->pdf) {
               return $this;
           }

           $this->beforeRender();

           $template = sprintf('invoices::templates.%s', $this->template);
           
           $this->pdf = PDF::loadView($template, ['invoice' => $this]);
           $this->output = $this->pdf->stream('invoice.pdf');

           return $this;
       }
   }
   ```

**Modify the Default Blade Template**: Open `default.blade.php` and remove `media="screen"` from the `<style>` tag.
   ```html
   <!-- Replace this: -->
   <style type="text/css" media="screen">

   <!-- With this: -->
   <style type="text/css">
   ```

**Use the Custom Invoice Class in Your Controller**: With this setup, your invoices should display Arabic characters correctly.

![image](https://github.com/user-attachments/assets/3f81b5c5-c061-4e52-a154-9976c60450af)
