### ISSUE TITLE
Making it service related invoice

### ISSUE THREAD

**Issue by sharik709** [LaravelDaily/laravel-invoices#8]
**Is your feature request related to a problem? Please describe.**
I'm trying to generate service invoice but i'm asked by client to disable qty and unit per price and series.

**Describe the solution you'd like**
What I'm missing in class that it doesn't have any methods to control the view. (please tell me if I'm wrong). I'm going to contribute to this package by making it able to work with service type invoice and control some obvious view options.

**Describe alternatives you've considered**
Haven't considered anything else at the moment

**Additional context**
The reason why i'm writing here is because before i work i wanna make sure that it doesn't exists or just have some ideas from the author or someone interested in it. 

Thank you for awesome package. I would love to contribute and help more :)

**Comment by PovilasKorop** [comment]
@sharik709 disable qty and unit per price and series?
What is left then from invoice? I've never seen an example of such invoice. Can you send me an example PDF or any link where people issue such invoices?

**Comment by sharik709** [comment]
yeah sure here is one from upwork https://bpyhf24739.i.lithium.com/t5/image/serverpage/image-id/7565iFFA0487EF2910AD7?v=1.0 

My first reaction was same. My client showed me this and asked to create something like this.

**Comment by PovilasKorop** [comment]
@sharik709 weird one. Well, no, we're not planning to make those optional. Qty can be 1, and unit per price can be 1. In that Upwork's invoice case, series is "T" and invoice number is 79162641.

**Comment by sharik709** [comment]
oh ok. I'll fork it and add necessary things for this project but thank you for your quick response and explanation. I'm willing to contribute to the this package. Please let me know if there is anything that I could help contribute.

**Comment by mc0de** [comment]
@sharik709 just have a default value of quantity to 1 in your service, and remove unnecessary data from template.

**Comment by sharik709** [comment]
@mc0de that's what I suggested to my client but he refused 🌵 . So, I just modified this package.
