### ISSUE TITLE
Adding details under service title

### ISSUE THREAD

**Issue by WebMedic-X** [LaravelDaily/laravel-invoices#82]
Hi,

Upgraded to the latest Laravel 8.x for this package btw haha, thanks for the push.

Now using the invoices and it works fine, the invoice is missing something though.

Currently each item has just a title, in real life scenarios sometimes we need to add descriptions and a list of deliverables/features under each title.

Which now seems not possible with the default functions of the InvoiceItem.

Is there a way to extend it to do that?

End result:

```
Invoice Line Title
- List
- Of
- Features / Deliverables
```

Thank you

**Comment by stefanlam88** [comment]
temporary i guess u can json_encode method first while waiting available method in next release

**Comment by mc0de** [comment]
@WebMedic-X i will add this a bit later when my schedule frees up a bit, not closing for now and thank you for feedback

**Comment by mc0de** [comment]
PR for this feature accepted and release will be later today with v2.1
