### ISSUE TITLE
PHP 8 pdf dom problem

### ISSUE THREAD

**Issue by Greenvold** [LaravelDaily/laravel-invoices#84]
Hi,

There is probably an issue with php 8. It is connected to dom pdf compatibility issue with php8. the error states following

Required parameter $dompdf follows optional parameter $paper.

I found github forum post where they are fixing this by changing the dom pdf version [here](https://github.com/barryvdh/laravel-dompdf/issues/747)

Do you think you could look into that and maybe change the dompdf version required?

Thank you very much.

**Comment by mc0de** [comment]
Hi,
we do not use dompdf directly, and barryvdh/laravel-dompdf is already updated

have you tried running `composer update`?

**Comment by jmrafael** [comment]
just run composer update and still getting the error
![image](https://user-images.githubusercontent.com/33831855/131230599-0e37926b-32d6-402a-8ee7-366801da647a.png)
