### ISSUE TITLE
Class "NumberFormatter" not found

### ISSUE THREAD

**Issue by jade-creator** [LaravelDaily/laravel-invoices#85]
Hi,

I have already deployed my laravel 8 app and with the latest version of this package.

However, when I try to access the url to generate the invoice I get prompted with a 500 error, though it works in local env.
I have temporarily set the APP_DEBUG to true to see it:

**Error** > **ViewException** 

Class "NumberFormatter" not found (View: /app/resources/views/vendor/invoices/templates/default.blade.php)

and it points at /Traits/CurrencyFormatter.php (line 154) in getAmountInWords():

`$formatter = new NumberFormatter($locale ?? App::getLocale(), NumberFormatter::SPELLOUT);`

Is there any workaround that I can do to make it work? Though I don't think it is possible so I'm just hoping for any response.
Thank you! 🙂

**Comment by PovilasKorop** [comment]
@jade-creator before raising the issue, please search for previous similar ones: https://github.com/LaravelDaily/laravel-invoices/issues?q=is%3Aissue+numberformatter

Closing as duplicate.

**Comment by jade-creator** [comment]
Really sorry for the trouble. I will always keep that in mind. Thank you so
much, awesome package!
