### ISSUE TITLE
Barcode on every invoices created

### ISSUE THREAD

**Issue by bintangjtobing** [LaravelDaily/laravel-invoices#88]
Hi creator,
You're great!

And I've just thought about the QR-code, which is invoicing system will be greater with using QR-code integrated with a controller on laravel.

So, when the reader reads the QR-code, it will run a link that the developer set on web.php.

I know you should more understand than me.. hehe

**Comment by PovilasKorop** [comment]
@bintangjtobing we're not planning this feature (or any new features) at the moment in this package.

But if you want to build it, we may accept Pull Request.
