### ISSUE TITLE
How come there is no shipping

### ISSUE THREAD

**Issue by osuagwu** [LaravelDaily/laravel-invoices#9]
I have implemented this package before finding out that there is no way to add shipping. So there is no way to make the invoice add up to the amount customer paid because shipping is not being added. How come there is no shipping? it often show up in invoices or am I missing something here?

**Comment by PovilasKorop** [comment]
@osuagwu in our projects and in our cases we don't use/have shipping tax, so we didn't implement it. But now you're the second person requesting it, so probably it's useful. Will implement later in February, the discussion will be in the original #6 issue, closing this one as a duplicate.
