### ISSUE TITLE
How can we make the total of quantity?

### ISSUE THREAD

**Issue by bintangjtobing** [LaravelDaily/laravel-invoices#90]
Hello author,
Can we make the total quantity without having required the price?
Because when I commented on the price, it has errors shows that require a price.

![image](https://user-images.githubusercontent.com/47741235/124720784-b4d2ba00-df32-11eb-940a-21608118eb11.png)
I want to make the total amount is a total quantity without the price.

Is it possible sir?

**Comment by mc0de** [comment]
@bintangjtobing set price to 1 Rp.

**Comment by bintangjtobing** [comment]
What do you mean sir?
I mean to make a total of quantity sir.

So that i wanna make one new function.
Is it possible?
