### ISSUE TITLE
title in tab menu always appears - 1

### ISSUE THREAD

**Issue by bintangjtobing** [LaravelDaily/laravel-invoices#91]
How can i change the title sir?
From, 
![image](https://user-images.githubusercontent.com/47741235/125913185-a7640829-b8e6-418c-a73f-9b92919bbc15.png)

to be like,
Purchase Invoice - [SERIAL _ NO]

Thank you, sir.

**Comment by mc0de** [comment]
just update invoice template `default.blade.php` tag `<title>{{ $invoice->name }}</title>` with anything you want
