### ISSUE TITLE
add RTL direction 

### ISSUE THREAD

**Issue by salimedia** [LaravelDaily/laravel-invoices#96]
**add RTL direction to this package**

First I would like to thank you for this package,
But when I need to export a PDF file in right-to-left languages i find a problem.
Is there a solution?
Thank you all
Salim

**Comment by mc0de** [comment]
@salimedia hi and thank you for good word

for RTL support you need to make a custom template: https://github.com/LaravelDaily/laravel-invoices#templates

unfortunately we do not have plans to add it in near future, but instead would accept PR
