### ISSUE TITLE
Undefined variable: invoice (View: 

### ISSUE THREAD

**Issue by abanghendri** [LaravelDaily/laravel-invoices#98]
**Describe the bug**
Undefined variable: invoice (View: E:\laragon\www\larasaas\resources\views\vendor\invoices\templates\mytemplate.blade.php) 

I make my own template, but it says Undefined variable:invoice

I use Invoice::make()->template('mytemplate')

thanks in advance

**Comment by mc0de** [comment]
not sufficient information, I just tested that and it works as expected

you need to provide seller, buyer and addItems to make it work

```PHP
        $test = Invoice::make()
            ->seller($client)
            ->buyer($customer)
            ->addItems($items)
            ->template('custom');

        return $test->stream();
```
