### ISSUE TITLE
Method Illuminate\View\View::__toString() must not throw an exception

### ISSUE THREAD

**Issue by UltraSoftware0** [LaravelDaily/laravel-invoices#99]
when calling the function to create an invoice this error pops out 
Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: Class 'NumberFormatter' not found (View: E:\projects\SBS\Accounting\resources\views\vendor\invoices\templates\default.blade.php) 

usually the invoice should be created with out any errors this is the first time this has happened 
the line wich is throwing the exeption: 
            $html     = mb_convert_encoding($view, 'HTML-ENTITIES', 'UTF-8');

used on chrome browswer laravel 8 

I guess it is because of the php version, I have changed it today

**Comment by mc0de** [comment]
please search previous issues before posting a new one, this one has been explained several times

https://github.com/LaravelDaily/laravel-invoices/issues?q=is%3Aissue+NumberFormatter

**Comment by UltraSoftware0** [comment]
thank you noted.
